### ISSUE TITLE
Any plans to create or release smaller models (3B, 1B)?

### ISSUE THREAD

**Issue by sozforex** [meta-llama/codellama#100]
Hi! Do you have any plans to create or release smaller Code Llama models?
They may be of use to speed-up inference via speculative sampling (https://github.com/ggerganov/llama.cpp/pull/2926).

**Comment by jspisak** [comment]
thanks for the request - this is definitely something the community has been asking for. We are in roadmap planning now and we will take this into account. Btw love the GGML work!
