### ISSUE TITLE
Download sh not working

### ISSUE THREAD

**Issue by Kainkainkain** [meta-llama/codellama#107]
[x] Visit the Meta AI website and accept the License agreement.
Done

[x] Wait for approval, and you will receive a signed URL via email.
Done

[] Run the download.sh script and pass the provided URL when prompted to initiate the download. Ensure you copy the URL text itself, not using the 'Copy link address' option.
Get error

[x] Ensure you have wget and
[x]  md5sum installed as prerequisites.
Done

[] Run the script by executing "bash download.sh."
Error

[x] Be aware that the download links expire after 24 hours and a certain number of downloads. If you encounter a "403: Forbidden" error, you can request a new link.
(just downloaded, haven't been able to get prompt yet).

[x] I also ran `pip install -e .`

This is the response in cmd:

```
\GitHub\codellama>bash download.sh
download.sh: line 2: $'\r': command not found
download.sh: line 5: $'\r': command not found
': not a valid identifier: `PRESIGNED_URL

': not a valid identifier: `MODEL_SIZE
download.sh: line 12: $'\r': command not found
download.sh: line 22: syntax error near unexpected token `$'do\r''
'ownload.sh: line 22: `do
```
```
codellama>bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
. ```


Perhaps I missed something?
I've successfully been running other models in python on this PC.

**Comment by D4rkMoons** [comment]
Youre problem is that it looks like your using cygwin or anything windows
Use Linux
you can see the `'/'` on linux and `"\"`

![image](https://github.com/facebookresearch/codellama/assets/77543961/723ee59b-8199-4e63-b3e9-59c968810d99)

**Comment by Kainkainkain** [comment]
Ah ok I'll try WSL maybe then.

**Comment by Kainkainkain** [comment]
@D4rkMoons I'm unsure your screenshot is this the right reply?

**Comment by isaacayz** [comment]
Has this been resolved or do you still need help?

**Comment by syhw** [comment]
@Kainkainkain the advice in the thread is correct, either change the script to use Windows style escapes (and hope that this is sufficient for your cygwin bash to work), or use WSL/linux.

**Comment by D4rkMoons** [comment]
@Kainkainkain Yep this is the right Place :) ; My way of expression might have been Tempered by talkin to many chatGPT's 😅
Altho dont even remember replying 🤦‍♂️ 
But yea ... ✌🐧
Linux     =" / " |   WinDos =" \ "
