### ISSUE TITLE
Unable to get complete output and seems pending while running 13b-instruct

### ISSUE THREAD

**Issue by i-love-doufunao** [meta-llama/codellama#109]
I cloned and deployed the project locally from https://huggingface.co/spaces/codellama/codellama-13b-chat/tree/main. But after I run this 13b-instruct model,I find there are two issues:

1. model always doesn't provide me complete answer.I try to track the ouput of model and find that it seems to repeat to print empty string until length of output exceeds max_new_token like this:
<img width="642" alt="no complete answer" src="https://github.com/facebookresearch/codellama/assets/42244960/84be5304-595b-402d-921b-80e811a130a7">

2. model output duplicate content until length exceeds max_new_token.
instruction:write a c++ code to do quick sort.

<img width="314" alt="duplicate" src="https://github.com/facebookresearch/codellama/assets/42244960/2d18b030-2ab1-4808-9703-85e8ed4da382">

current configuration:Top-k:10 Top-p:0.1 Temperature:0.7 Max new tokens:1024 I tried to fine-tune these parameters with little success.
Could anybody share any ideas to address this strange issue?

**Comment by syhw** [comment]
Hi, this can be due to several factors: either you're not using the correct tokenizer (in HugginFace's code you need to specify the Code Llama tokenizer, as it at least used to be the Llama 2 tokenizer by default), or you didn't wrap your instructions in `[INST][/INST]` if you're serving it barebones with your own serving script.

**Comment by syhw** [comment]
Let us know if that fixes it!

**Comment by i-love-doufunao** [comment]
> Let us know if that fixes it!

Thanks for your reply, I've review codellama demo description again and found that the version of transformers in my demo is lower than 4.33, so I upgraded it to 4.33 and this issue seems fixed.
