### ISSUE TITLE
The difference between the playground and the offline model

### ISSUE THREAD

**Issue by cocovoc** [meta-llama/codellama#116]
I cannot reproduce the equivalent output using the offline model (codellama/CodeLlama-13b-Instruct-hf, https://huggingface.co/codellama/CodeLlama-13b-Instruct-hf)

Here are some offline examples. 

![截屏2023-09-14 23 18 11](https://github.com/facebookresearch/codellama/assets/22885358/c8776063-2558-4ae7-a91d-05499156c0f6)

The Playground example (using https://huggingface.co/spaces/codellama/codellama-13b-chat)
![截屏2023-09-14 22 44 28](https://github.com/facebookresearch/codellama/assets/22885358/43261440-e281-4646-b0fd-5f96e65ae535)

The performance of the offline huggingface model is poor, which is worse than that of playground. Is there something wrong with hyperparameter settings? 

Is the model used in playground different from the offline download model?

Huggingface code: 
```python
tokenizer = CodeLlamaTokenizer.from_pretrained(path_model_id) 
   model = LlamaForCausalLM.from_pretrained( 
    path_model_id, 
    torch_dtype=torch.float16 
).to("cuda:0")
```
```python 
user = "Write a function that computes the set of sums of all contiguous sublists of a given list."
prompt = f"<s>[INST]{user.strip()} [/INST]"
input_ids = tokenizer(prompt, return_tensors="pt")["input_ids"].to("cuda:0")
output = model.generate(
    input_ids,
    max_new_tokens=2000,
    # top_p=0.9,
    # temperature=0.1,
    # # top_k=10,
    # do_sample=True,
    # num_beams=1,
    # repetition_penalty=1.1,
    repetition_penalty=1.05,
    # eos_token_id=tokenizer.eos_token_id,
    # pad_token_id=tokenizer.pad_token_id
)
output = output[0].to("cpu")

filling = tokenizer.decode(output[input_ids.shape[1]:], skip_special_tokens=True)
print(filling)
```

**Comment by HongYukai** [comment]
I meet the same problem when using codellama/CodeLlama-34b-Instruct-hf. Who can resolve this issue please?

**Comment by faabian** [comment]
Thank you for reporting @cocovoc and @HongYukai !
As this issue pertains to the HuggingFace implementation of our models, please direct your question to https://github.com/huggingface/transformers/

That said, note you can view the source code of the playground example here https://huggingface.co/spaces/codellama/codellama-13b-chat/tree/main and compare, and that such issues are usually related to the exact formatting and tokenizations. In particular, you may want to check how HF handles `<s>`.

**Comment by for-just-we** [comment]
> I cannot reproduce the equivalent output using the offline model (codellama/CodeLlama-13b-Instruct-hf, https://huggingface.co/codellama/CodeLlama-13b-Instruct-hf)
> 
> Here are some offline examples.
> 
> ![截屏2023-09-14 23 18 11](https://user-images.githubusercontent.com/22885358/268023932-c8776063-2558-4ae7-a91d-05499156c0f6.png)
> 
> The Playground example (using https://huggingface.co/spaces/codellama/codellama-13b-chat) ![截屏2023-09-14 22 44 28](https://user-images.githubusercontent.com/22885358/268013750-43261440-e281-4646-b0fd-5f96e65ae535.png)
> 
> The performance of the offline huggingface model is poor, which is worse than that of playground. Is there something wrong with hyperparameter settings?
> 
> Is the model used in playground different from the offline download model?
> 
> Huggingface code:
> 
> ```python
> tokenizer = CodeLlamaTokenizer.from_pretrained(path_model_id) 
>    model = LlamaForCausalLM.from_pretrained( 
>     path_model_id, 
>     torch_dtype=torch.float16 
> ).to("cuda:0")
> ```
> 
> ```python
> user = "Write a function that computes the set of sums of all contiguous sublists of a given list."
> prompt = f"<s>[INST]{user.strip()} [/INST]"
> input_ids = tokenizer(prompt, return_tensors="pt")["input_ids"].to("cuda:0")
> output = model.generate(
>     input_ids,
>     max_new_tokens=2000,
>     # top_p=0.9,
>     # temperature=0.1,
>     # # top_k=10,
>     # do_sample=True,
>     # num_beams=1,
>     # repetition_penalty=1.1,
>     repetition_penalty=1.05,
>     # eos_token_id=tokenizer.eos_token_id,
>     # pad_token_id=tokenizer.pad_token_id
> )
> output = output[0].to("cpu")
> 
> filling = tokenizer.decode(output[input_ids.shape[1]:], skip_special_tokens=True)
> print(filling)
> ```

I also notice in my task, I locally run the huggingface model of 7b-Instruct,13b-Instruct and original format of 7b-Instruct,13b-Instruct. I found the performance of huggingface model is worse than original format model, like be got IQ down, I don't know why
