### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by zhenganglu** [meta-llama/codellama#118]
I am getting the following error when I tried to run the example with "torchrun  example_completion.py     --ckpt_dir CodeLlama-7b/     --tokenizer_path CodeLlama-7b/tokenizer.model     --max_seq_len 128 --max_batch_size 4".

I have PyTorch 2.0.1 installed on WSL2 using miniconda. Unlike other issues where "torch.distributed.elastic.multiprocessing.api:failed" with an existcode 1, I am getting SIGKILL. What could be the reason?

> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 29066) of binary: /home/zlu/miniconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/zlu/miniconda3/envs/torch/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zlu/miniconda3/envs/torch/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/zlu/miniconda3/envs/torch/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/zlu/miniconda3/envs/torch/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/zlu/miniconda3/envs/torch/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zlu/miniconda3/envs/torch/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
example_completion.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-16_15:03:11
  host      : Lenovo21.
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 29066)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 29066
======================================================

**Comment by ashantanu** [comment]
facing the same issue

**Comment by zhenganglu** [comment]
Same issue when running using PyTorch nightly preview with cuda 12.1 in another conda environment.

**Comment by CodingFlow** [comment]
I'm having the same issue and I suspect it is because my machine ran out of ram memory per [this comment](https://github.com/facebookresearch/codellama/issues/30#issuecomment-1694332808).

**Comment by zhenganglu** [comment]
It looks like both the VM and GPU needs 16 GB of memory to run the example.
