### ISSUE TITLE
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default？

### ISSUE THREAD

**Issue by LinJia21** [meta-llama/codellama#123]
torchrun --nproc_per_node 2 example_infilling.py --ckpt_dir CodeLlama-13b-Python/ --tokenizer_path CodeLlama-13b-Python/tokenizer.model --max_seq_len 192 --max_batch_size 4
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

**Comment by LinJia21** [comment]
and I set OMP_NUM_THREADS=1 torchrun --nproc_per_node 2 example_infilling.py --ckpt_dir CodeLlama-13b-Python/ --tokenizer_path CodeLlama-13b-Python/tokenizer.model --max_seq_len 192 --max_batch_size 4.

**Comment by LinJia21** [comment]
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 10621 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 10622) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/lin/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/lin/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/lin/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/lin/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/lin/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lin/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by LinJia21** [comment]
set below to the run demo.py :
local_rank = 0
torch.cuda.set_device(local_rank)
also error:RuntimeError: CUDA error: invalid device ordinal

**Comment by mpu** [comment]
Hello LinJia21,

your system must have multiple GPUs to run models >= 13b.
