### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by ensorrow** [meta-llama/codellama#126]
Changing `model.py` like this can fix this problem, maybe there is a better solution:

![image](https://github.com/facebookresearch/codellama/assets/13199771/c2c8a213-a262-4c78-8d41-5488e9a587c1)

**Comment by mpu** [comment]
Should be fixed by PR #127. Thanks for flagging it.
