### ISSUE TITLE
Combining instruction and infilling

### ISSUE THREAD

**Issue by kherud** [meta-llama/codellama#139]
Figure 2 of the paper shows the training pipeline of all models. Each model undergoes infilling code training. For the instruct models additionally a final instruction fine-tuning is applied. This suggests that both tasks can be combined. However, the paper doesn't make this clear to me and the code examples also seem to only do one thing at a time.

- Is is possible to combine instructing and infilling in a single prompt?
- If yes, what is the correct prompt format?

I imagine something like

```
[INST][SYS] system [/SYS] instruction [/INST][PREFIX] prefix [SUFFIX] suffix [MID] 
```

**Comment by jgehring** [comment]
Hi @kherud, you're right in that we didn't test this specifically but it'll be interesting to try for sure. You can follow the code in [generate.py](https://github.com/facebookresearch/codellama/blob/main/llama/generation.py) to retrieve the correct formatting, the system message should be formatted differently. You can use [`infilling_prompt_tokens()`](https://github.com/facebookresearch/codellama/blob/e66609cfbd73503ef25e597fd82c59084836155d/llama/generation.py#L396) to tokenize the non-instruction part. It might be worth testing if the system and instruction prompts could be part of the prefix as well.

**Comment by yujonglee** [comment]
@kherud  Would you mind sharing your findings on this?

**Comment by jhcordeiro** [comment]
@jgehring @kherud did you have a change to study this further? I'd love to read the results if so
