### ISSUE TITLE
How to trigger the model?

### ISSUE THREAD

**Issue by Starlord22** [meta-llama/codellama#14]
I got the following - how do I trigger the model GUI? 

(codegenllama) C:\>pip install -e codellama
Obtaining file:///C:/codellama
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from codellama==0.0.1) (2.0.1+cu117)
Collecting fairscale (from codellama==0.0.1)
  Downloading fairscale-0.4.13.tar.gz (266 kB)
     ---------------------------------------- 266.3/266.3 kB 5.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fire (from codellama==0.0.1)
  Downloading fire-0.5.0.tar.gz (88 kB)
     ---------------------------------------- 88.3/88.3 kB 5.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting sentencepiece (from codellama==0.0.1)
  Downloading sentencepiece-0.1.99-cp310-cp310-win_amd64.whl (977 kB)
     ---------------------------------------- 977.5/977.5 kB 10.3 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.22.0 in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from fairscale->codellama==0.0.1) (1.24.1)
Requirement already satisfied: filelock in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from torch->codellama==0.0.1) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from torch->codellama==0.0.1) (4.4.0)
Requirement already satisfied: sympy in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from torch->codellama==0.0.1) (1.11.1)
Requirement already satisfied: networkx in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from torch->codellama==0.0.1) (3.0)
Requirement already satisfied: jinja2 in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from torch->codellama==0.0.1) (3.1.2)
Collecting six (from fire->codellama==0.0.1)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting termcolor (from fire->codellama==0.0.1)
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from jinja2->torch->codellama==0.0.1) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\home\anaconda3\envs\codegenllama\lib\site-packages (from sympy->torch->codellama==0.0.1) (1.2.1)
Building wheels for collected packages: fairscale, fire
  Building wheel for fairscale (pyproject.toml) ... done
  Created wheel for fairscale: filename=fairscale-0.4.13-py3-none-any.whl size=332117 sha256=0945c01902555985db3ce29135a6b2eef4448b83305b47dbb614485d15188a24
  Stored in directory: c:\users\home\appdata\local\pip\cache\wheels\78\a4\c0\fb0a7ef03cff161611c3fa40c6cf898f76e58ec421b88e8cb3
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl size=116947 sha256=d2a6f24d8bb7ed4b42b780a7fcdbae383514bf5ef87b37c07ab76410ca582514
  Stored in directory: c:\users\home\appdata\local\pip\cache\wheels\90\d4\f7\9404e5db0116bd4d43e5666eaa3e70ab53723e1e3ea40c9a95
Successfully built fairscale fire
Installing collected packages: sentencepiece, termcolor, six, fire, fairscale, codellama
  Running setup.py develop for codellama
Successfully installed codellama-0.0.1 fairscale-0.4.13 fire-0.5.0 sentencepiece-0.1.99 six-1.16.0 termcolor-2.3.0

**Comment by faabian** [comment]
There is no GUI. Please refer to the [README](https://github.com/facebookresearch/codellama/blob/main/README.md) for instructions and examples for usage.
You can also play with the model on Hugging Face's playground: https://huggingface.co/spaces/codellama/codellama-playground
