### ISSUE TITLE
Can't reproduce the results on Humaneval

### ISSUE THREAD

**Issue by JulietLJY** [meta-llama/codellama#140]
Hello, may I ask how you conducted testing on Humaneval? I attempted to test using the two methods you provided in your Hugging Face blog, including code completion and code infilling on Humaneval. However, I only achieved results of 22% and 25% on Instruct CodeLLama 7B, which is far from the reported 35%.

```
args.max_length = 1024

if args.task == 'code-completion':
    tokenizer = transformers.AutoTokenizer.from_pretrained(args.model_path)
    pipeline = transformers.pipeline(
        "text-generation",
        model=args.model_path,
        torch_dtype=torch.float16,
        device_map="auto",
    )
    for task_id in problems:
        prompt = problems[task_id]['question'] + '<FILL_ME>\n    return result'
        input_ids = tokenizer(prompt, return_tensors="pt")["input_ids"].to("cuda")
        output = model.generate(input_ids, max_new_tokens=args.max_length,)
        output = output[0].to("cpu")
        filling = tokenizer.decode(output[input_ids.shape[1]:], skip_special_tokens=True)
        completion = prompt.replace("<FILL_ME>", filling)

elif args.task == 'code-infilling':
    tokenizer = transformers.AutoTokenizer.from_pretrained(args.model_path)
    model = transformers.AutoModelForCausalLM.from_pretrained(
        args.model_path,
        torch_dtype=torch.float16
    ).to("cuda")
    for task_id in problems:
        completion = pipeline(
            prompt,
            do_sample=True,
            temperature=0.2,
            top_p=0.9,
            num_return_sequences=1,
            eos_token_id=tokenizer.eos_token_id,
            max_length=args.max_length,
        )[0]['generated_text'].strip()

```

**Comment by jgehring** [comment]
Hi @JulietLJY, I'm a bit confused by the code sample you provided: you're using infilling for completion and completion for infilling (and this time with sampling)? For testing on HumanEval I'd suggest you try the [Code Generation LM Evaluation Harness](https://github.com/bigcode-project/bigcode-evaluation-harness#code-generation-lm-evaluation-harness). There will be small differences in results due to slight differences in prompt formatting and inference code but you should get results that are fairly close to what we reported.

**Comment by JulietLJY** [comment]
My issue has been effectively resolved. I appreciate your prompt response!

**Comment by harryhan618** [comment]
@JulietLJY Hi, may I ask a followup question? Have you reproduce the result of CodeLLama 7B pass@1 accuracy being 33.5%?
There is a (issue)[https://github.com/bigcode-project/bigcode-evaluation-harness/issues/220] in bigcode-evaluation-harness repo saying that he cannot reproduce either.
