### ISSUE TITLE
Codellama-7B can't  reproduce the paper's result 33.5%,why?

### ISSUE THREAD

**Issue by HotSummer888** [meta-llama/codellama#145]
I evaluated codellama 7b using greedy decoding, and the Humaneval result for pass@1 was only 28.66%. You are asking how to reproduce the paper's result of 33.5%.  pls show the evaluation parameters and prompt format. Here are some suggestions:
![image](https://github.com/facebookresearch/codellama/assets/142714958/fee2ace9-e64e-4745-a5f1-06cf2caa3423)

**Comment by jgehring** [comment]
I provided further details on HumanEval results in [this comment](https://github.com/facebookresearch/codellama/issues/104#issuecomment-1779575189); does this address your question?

**Comment by jgehring** [comment]
I've closed the issue, feel free to re-open if you have further questions.
