### ISSUE TITLE
What kind of prompt was used in HumanEval evaluation?

### ISSUE THREAD

**Issue by MacavityT** [meta-llama/codellama#157]
Thanks for your excellent work. I find there is no prompt for HumanEval completion task was released, could you give me some introduction?

**Comment by humza-sami** [comment]
Its same prompt which are for llama-2.

`<s>[INST] User message [/INST] Response </s>`

**Comment by jgehring** [comment]
See #104 for some discussion on this, specifically [this comment](https://github.com/facebookresearch/codellama/issues/104#issuecomment-1779575189). Feel free to reopen this if you have further questions.
