### ISSUE TITLE
Sorry, the download is not available in your region

### ISSUE THREAD

**Issue by Aruen24** [meta-llama/codellama#16]

**Comment by MrRace** [comment]
Download bias!!!!

**Comment by oukohou** [comment]
> Download bias!!!!

dude, you got any link for this bias? thanks

**Comment by GaganHonor** [comment]
Oh Don`t worry just use AWS ec2 free to use gpu instance of diffrent region , or just reply here i can help you step by step , still you can see this [Demo](https://huggingface.co/blog/codellama#conversational-instructions) 
![SurpriseShockGIF](https://github.com/facebookresearch/codellama/assets/141204441/ac0fc4bc-f435-42ba-9221-6ba126b29445)

**Comment by wusuhuang** [comment]
same question. how to do that?

**Comment by GaganHonor** [comment]
> same question. how to do that?

Go visit AWS sagemaker

**Comment by ColorStar71** [comment]
Download bias!

**Comment by Rajjaa** [comment]
I can't access LLama 2 from Morocco. I am getting "Sorry, the download is not available in your region"

**Comment by tula-liuxin** [comment]
It's runned my fantasy of so called humanity.

**Comment by tula-liuxin** [comment]
It's ruined my fantasy of so called humanity.

**Comment by sunfeng90** [comment]
How to solve this?
