### ISSUE TITLE
Download URL from the email gives me Llama code, not Llama 2

### ISSUE THREAD

**Issue by aimagician** [meta-llama/codellama#163]
I get an email with a download URL, but when I run a download URL, I get these options:
**Enter the list of models to download without spaces (7b,13b,34b,7b-Python,13b-Python,34b-Python,7b-Instruct,13b-Instruct,34b-Instruct), or press Enter for all:** 

I do not see these models as per email:
Llama-2-7b
Llama-2-7b-chat
Llama-2-13b
Llama-2-13b-chat
Llama-2-70b
Llama-2-70b-chat

Am I doing anything wrong?

**Comment by dveb8886** [comment]
These look like they correspond to the chat variant of llama 2 (this repo: https://github.com/facebookresearch/llama)

When you requested access to llama, you had the opportunity to select which model you want, the current repo you filed the issue for corresponds to the code variant.

The code and chat variants arrived in different emails for me, so check your email if you requested both
