### ISSUE TITLE
I'd like to know if this is the right type of dataset for the model using the infilling function.

### ISSUE THREAD

**Issue by Yindy07** [meta-llama/codellama#174]
Thanks for your excellent work.
I want to make a model that uses the infilling function, but the type of dataset I use right now is  
[PRE]{prefix} [SUF]{suffix}[MID]{example['answer']} [EOT]
It is in form and based on [FILL], the front prefix and the back of the prefix were divided by suffix. When [FILL]  << the data to be entered here is {example['answer']}, it is taught by attaching it after [MID>] is it the correct method to learn with this type of dataset?

**Comment by gunwooleee** [comment]
I'm curious too.

**Comment by allenliu88** [comment]
@Yindy07 did you have any ideas?
