### ISSUE TITLE
Questions about learning more than 4096 sequences in codellama

### ISSUE THREAD

**Issue by ParkRio** [meta-llama/codellama#175]
hello

I had a question and wanted to get some ideas, so I registered an issue.

Now, I'm sorry that I don't have much knowledge as it's been a while since I studied LLM.

I don't speak English, so I wrote it through a translator, so the words may sound strange.

Currently, I try to fine-tuning infilling capability from one node to four GPUs of the codellama 7b or 13b models using deepspeed, but if the sequence length of the dataset to be trained exceeds 4096 supported by codellama, whether it is not suitable for learning infilling, or is there any other way or good ideas to learn
I want to know.

thank you

**Comment by jgehring** [comment]
Hi @ParkRio, longer sequences can be used for fine-tuning with or without infilling. Code Llama supports sequences of up to 100k tokens. If you’re able to do multiple fine-tuning runs it may be a good idea to test for multiple lengths and pick the one that works best for you. It’s a tradeoff between resources required for inference (longer context requires more memory and takes longer), the ability to recall information in the context (Code Llama as-is works very well up to 16k tokens but fine-tuning could further expand on that), and what your application requires.

**Comment by ParksangwookA** [comment]
> Hi @ParkRio, longer sequences can be used for fine-tuning with or without infilling. Code Llama supports sequences of up to 100k tokens. If you’re able to do multiple fine-tuning runs it may be a good idea to test for multiple lengths and pick the one that works best for you. It’s a tradeoff between resources required for inference (longer context requires more memory and takes longer), the ability to recall information in the context (Code Llama as-is works very well up to 16k tokens but fine-tuning could further expand on that), and what your application requires.

Thank you for your kind explanation.

**Comment by ParkRio** [comment]
@jgehring 
Thank you very much for your kind explanation!!
