### ISSUE TITLE
Meta AI response "bug" 

### ISSUE THREAD

**Issue by ThinkName3341** [meta-llama/codellama#183]
Any time I ask certain questions like "what is your favorite color" the AI will respond with "ah! Ah! Ah! Ah!"
But like 50 "ah!"s
![Screenshot_20240117-212142~2](https://github.com/facebookresearch/codellama/assets/156983217/13c2aa7d-17b8-4fb3-821e-b464018e7f39)

**Comment by jgehring** [comment]
Sorry, this is outside of the scope of this project.
