### ISSUE TITLE
Annoying, Non-User-Friendly Download Script

### ISSUE THREAD

**Issue by Tom-Neverwinter** [meta-llama/codellama#189]
Summary: The current script for downloading models, while supposedly secure, leaves much to be desired in terms of user experience. It's a classic case of over-engineering, where the effort to enhance security and versatility results in a cumbersome and less intuitive process.

Problems Identified:

Lack of Clarity: Users are often puzzled about the format for selecting models to download, leading to wasted attempts and frustration.
No Interactive Guidance: The script lacks interactive elements, such as pauses or clear instructions, making it daunting for less experienced users.
Python Environment Checks Missing: The script does not verify the presence of required Python environments beforehand, leading to last-minute errors and confusion.
Inconvenient Post-Download Process: Users are left with the task of manually managing downloaded files, adding unnecessary post-download work.
Proposed Solutions:

Enhance Clarity: Revise the script to include explicit instructions about the format for model selection.
Improve Interactivity: Integrate user prompts and pause functions for a more guided experience.
Environment Validation: Implement checks for necessary Python environments before initiating downloads.
Automate Cleanup: Optionally, add a feature to automatically delete files post-verification, reducing user workload.
Conclusion:
The aim is to transform this digital equivalent of a "needle in a haystack" search into a more straightforward, less infuriating experience. Because let's face it, the current script is like a puzzle where you're unsure if the pieces are missing or you just can't see the bigger picture.

pyenv git and md5, verify selected downloads, verify where to download. download. verify. cleanup and complete. 
may as well do it all and make it secure. 

Joke: echo "Congratulations, you've successfully navigated the labyrinth of our 'user-friendly' download script. Just think of it as a digital scavenger hunt, but instead of treasure, you get model files. Enjoy deciphering them! 🤷‍♂️"

**Comment by phamkinhquoc2002** [comment]
facts

**Comment by phamkinhquoc2002** [comment]
I have troubble downloading as im using windows, and the wsl confusing me

**Comment by unphased** [comment]
If whatever model files you're after were put on huggingface, you can grab them very easily and reliably by having `git-lfs` installed on your machine and `git clone https://hf.co/<repo path>`.

**Comment by Tom-Neverwinter** [comment]
> If whatever model files you're after were put on huggingface, you can grab them very easily and reliably by having `git-lfs` installed on your machine and `git clone https://hf.co/<repo path>`.

yeah, it would be much easier. agree to the terms and then download however you want even using jdownloader to check integrity and move to desired location. instead we have the "EA launcher" of AI

**Comment by coloradokb** [comment]
I'm very interested in this, however, just like the details in issue 176 (https://github.com/facebookresearch/codellama/issues/176) I am also getting forbidden, bad schema, 416 Requested Range Not Satisfiable. I've gone through the accepting license form page and link(s) I get are the same and in past 4 hours of this post. Oh well, will try again later in the week.

**Comment by Tom-Neverwinter** [comment]
The Bloke seems to have quantized the model already, so no reason to waste time on this anymore. 

https://huggingface.co/TheBloke
