### ISSUE TITLE
line 1: payload:allShortcutsEnabled:false: command not found

### ISSUE THREAD

**Issue by AKA-Axanar** [meta-llama/codellama#191]
when I run the download.sh script in bash I get this error:
line 1: payload:allShortcutsEnabled:false: command not found

How do I fix this?

Thank you.

**Comment by AKA-Axanar** [comment]
BTW, I get the same error in an Ubuntu VM and on Windows.

**Comment by jgehring** [comment]
That doesn't sound right, can you check whether your copy of `download.sh` starts with the following lines?

```bash
#!/bin/bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# This software may be used and distributed according to the terms of the Llama 2 Community License Agreement.

read -p "Enter the URL from email: " PRESIGNED_URL
```

**Comment by AKA-Axanar** [comment]
It does not.  it starts like this and is all in one long single line:
{"payload":{"allShortcutsEnabled":false,"fileTree":{"":{"items":[{"name":".circleci","path":".circleci","contentType":"directory"},{"name":"llama","path":"llama","contentType":"directory"},

Thank you.

**Comment by jgehring** [comment]
Hum, not sure what went wrong here, but that's certainly not the correct script. Can you try cloning this whole repository with `git clone https://github.com/facebookresearch/codellama` and then run download.sh from the resulting directory (codellama)?

**Comment by AKA-Axanar** [comment]
I downloaded just the sh file from github and it's now downloading fine in an Ubuntu VM.  Thank you for your help.
