### ISSUE TITLE
Checksum failures for 70B Instruct (and Python) 

### ISSUE THREAD

**Issue by fourpartswater** [meta-llama/codellama#192]
I am getting a checksum failures for 70B Instruct and Python:

CodeLlama-70b-Instruct:
Checking checksums
Warning: Hash size is wrong, maybe you want to use 'sha1sum' or 'ripemd160sum'
consolidated.00.pth: FAILED
consolidated.01.pth: OK
consolidated.02.pth: OK
consolidated.03.pth: OK
consolidated.04.pth: OK
consolidated.05.pth: OK
consolidated.06.pth: OK
consolidated.07.pth: OK
params.json: FAILED
tokenizer.model: OK
md5sum: WARNING: 2 of 10 computed checksums did NOT match

CodeLlama-70b-Python:
Checking checksums
consolidated.00.pth: OK
consolidated.01.pth: OK
consolidated.02.pth: OK
consolidated.03.pth: OK
consolidated.04.pth: OK
consolidated.05.pth: OK
consolidated.06.pth: OK
consolidated.07.pth: OK
params.json: FAILED
tokenizer.model: OK

**Comment by fourpartswater** [comment]
The params errors seem to be the same as #188

**Comment by fourpartswater** [comment]
I tried downloading CodeLlama-70b-Instruct consolidated.00.pth multiple times with the same error.

**Comment by jgehring** [comment]
Hi @fourpartswater, thanks for the notice! Indeed, there was an error in the checksum files for CodeLlama-70b-Python and CodeLlama-70b-Instruct. If you download these models again you should get the updated versions. For reference (and to maybe save you some download time), you can check that each `params.json` file (i.e., for CodeLlama-70b-Python and CodeLlama-70b-Instruct) has an MD5 checksum of `184c6afa048cf53e3f8755904556b2cb`.
