### ISSUE TITLE
Does it support FIM (fill-in-the-middle)?

### ISSUE THREAD

**Issue by xpl** [meta-llama/codellama#2]
This is useful for code completion tasks. Starcoder, for instance, is trained with FIM — how does Code LLama compare?

**Comment by StevenJohnston** [comment]
https://about.fb.com/news/2023/08/code-llama-ai-for-coding/

> The 7B and 13B base and instruct models have also been trained with fill-in-the-middle (FIM) capability

**Comment by zachschillaci27** [comment]
See the README for more info: https://github.com/facebookresearch/codellama#code-infilling
