### ISSUE TITLE
Requesting a Colab file to run code llama

### ISSUE THREAD

**Issue by Shivansh-Srivastava-techolution** [meta-llama/codellama#20]
Hey, 
Thank you very much for such a great work, it would be great if anyone can create a colab file where we can run this model.
In different regions we are not able to download the model weights and run it.
Thanking You in advance. : )

**Comment by Mraghuvaran** [comment]
https://colab.research.google.com/drive/1lyEj1SRw0B9I2UUI2HOrtiJ_fjvbXtA2?usp=sharing#scrollTo=eK1C84v0AyrX

**Comment by faabian** [comment]
thank you @Mraghuvaran
@Shivansh-Srivastava-techolution you can also take a look at the `README.md` for more examples, or at the implementation by HuggingFace: https://huggingface.co/blog/codellama#how-to-use-code-llama

closing this as solved.
