### ISSUE TITLE
Does codellama 13B/34B/70B support function calling and Lora fine tuning on multi-run chat with function calling?

### ISSUE THREAD

**Issue by zlfeng83** [meta-llama/codellama#201]
Does codellama 13B/34B/70B support function calling and Lora fine tuning on multi-run chat with function calling?
Are there any instruction pages about this? Thanks a lot.

**Comment by jgehring** [comment]
Hi @zlfeng83, Code Llama models have not be specifically trained or evaluated for function calling. However, I would think that it might be worth experimenting with it and maybe try to fine-tune it for these use-cases.

This repository does not support LoRA (or any fine-tuning for that matter), but there are several open-source projects offering this functionality.

Regarding multi-run chat: all instruction models support multi-turn prompts (i.e., user -> assistant -> user ->  assistant -> ... -> user) out of the box, while the other models can either be few-shot prompted or fine-tuned to support multi-turn chat given sufficient example data.
