### ISSUE TITLE
Where is the attribute `past_key_values`

### ISSUE THREAD

**Issue by XinyuShe** [meta-llama/codellama#205]
I hope to use `past_key_values` for inferring longer texts, but even though I have set `use_cache=True`, I still cannot find it in the `generated_tokens`'s attributes.
```python
generated_tokens = model.generate(
                **model_input, 
                max_new_tokens=1600,
                use_cache=True
                )
```

**Comment by jgehring** [comment]
Hi @XinyuShe, I'm not sure what you're referring to since the repo doesn't feature a `generate()` function like the one you're describing.
