### ISSUE TITLE
I'd like to know whether to use eos or bos during Code Llama pre-training

### ISSUE THREAD

**Issue by ChengMingZhang-ZTE** [meta-llama/codellama#206]
I am curious about the form of the dataset for Code Llama pre-training. I want to know whether eos or bos was used during the pre-training process. For example, the data format is {code}{EOS} or {BOS}{code}, which format is used for Code Llama pre-training?

**Comment by tangbo-sh** [comment]
I have same question.  When pre-training llama2(code llama), which one is used as the delimiter between samples: eos or bos?

**Comment by jgehring** [comment]
For training, we add both BOS and EOS tokens.

**Comment by tangbo-sh** [comment]
@jgehring I understand, thanks for your reply.
