### ISSUE TITLE
70B model memory issue

### ISSUE THREAD

**Issue by sanipanwala** [meta-llama/codellama#208]
Hello,

I have 2 GPU of 24 GB RTX 4090 GPU. 

I want to fine-tune the 70b model but it throws a **cuda out of memory exceptions** even though I have used Lora and BitsAndBytesConfig.

Let me know if I'm overlooking this or please give me suggestions.

Thanks.

**Comment by jgehring** [comment]
I can't really tell whether the configuration you provided is supposed to fit into your GPUs. If it doesn't work even with a batch size of 1, it's an indication that your hardware setup may not be sufficient. Try bringing this up to the maintainers or community of the tools you're using to fine-tune the model.
