### ISSUE TITLE
CodeLlama 中文text2sql效果如何？

### ISSUE THREAD

**Issue by njhouse365** [meta-llama/codellama#211]

**Comment by jgehring** [comment]
According to Google Translate, the English title is: "How effective is CodeLlama Chinese text2sql?"

I don't speak Chinese and don't know of a corresponding benchmark so I can't make a statement about these capabilities. If you're asking about a specific text-to-sql tuned model I'd recommended getting in touch with the creators of these fine-tuned versions.
