### ISSUE TITLE
SSL error when downloading

### ISSUE THREAD

**Issue by ankitkariryaa** [meta-llama/codellama#22]
Hi, 

The download script throws the following error:

```
Resolving download2.llamameta.net (download2.llamameta.net)... ::ffff:130.226.237.92, 130.226.237.92
Connecting to download2.llamameta.net (download2.llamameta.net)|::ffff:130.226.237.92|:443... connected.
OpenSSL: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
Unable to establish SSL connection.
Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found
```

If I set the `Options = UnsafeLegacyRenegotiation` in SSL conf then it throws the error mentioned in #8 . Thanks for the help!

**Comment by az-pz** [comment]
The download links expire after 24 hours. You may need to request the link again.

**Comment by adiyoss** [comment]
Hi @ankitkariryaa , 
@az-pz is correct the download links expire after 24 hours. Please request again the link.
