### ISSUE TITLE
how to finetune it locally

### ISSUE THREAD

**Issue by rajveer43** [meta-llama/codellama#24]

**Comment by faabian** [comment]
Please understand that we do not provide fine-tuning code in this repository. But you may want to take a look at this repository which applies to Code Llama just as it applies to Llama 2 and uses the HuggingFace transformers library: https://github.com/facebookresearch/llama-recipes/
Generally, all local finetuning methods developed in the last months for Llama also work with Code Llama, the main difference being the different value of `rope_theta` (see https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py for details).
