### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

### ISSUE THREAD

**Issue by ruokkkkk** [meta-llama/codellama#25]
https://colab.research.google.com/drive/1rXJyXXO4m-nP4XDoLV7h4_Iea3jYHDZY#scrollTo=xjpOpjPDAVQX
In google colab, When I execute fine-tuning it throws the error

**Comment by sanardicat** [comment]
same issue. I can run the infilling file, but not the prompt example.

**Comment by codingjlu** [comment]
Same here, I was watching the CPU RAM and that peaked to max, so that's probably why the program terminated.

**Comment by levy-tech-spark** [comment]
same issue.

**Comment by faabian** [comment]
Yes, this appears to be an out-of-memory error. You can try lowering the batch size and sequence length until it fits. Please feel free to re-open if the problem turns out not to be an out-of-memory error.
