### ISSUE TITLE
Model pads response with newlines up to max_length

### ISSUE THREAD

**Issue by marco-ve** [meta-llama/codellama#26]
I tried several of the models through Huggingface, and the response is always padded with newlines up to the number of tokens specified by the max_length argument in model.generate(). 

I also assign pad_token_id=tokenizer.eos_token_id, so I'm not sure why the model is generating these newline characters.

**Comment by borzunov** [comment]
I observe the same thing with [codellama/CodeLlama-34b-Instruct-hf](https://huggingface.co/codellama/CodeLlama-34b-Instruct-hf) on Hugging Face Hub. Quite often, the model starts to generate `\n` indefinitely instead of generating `</s>` and stopping.

This is using the standard generation params (`temperature=0.2, top_p=0.95`) with the prompt format and the example prompt suggested in this repository:

```
<s>[INST] <<SYS>>
A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.
<</SYS>>

In Bash, how do I list all text files in the current directory (excluding subdirectories) that have been modified in the last month? [/INST]
```

**Comment by Regenhardt** [comment]
This one made less newlines, but still way too many than needed:

`You're an intelligent, concise coding assistant. Wrap code in ``` for readability. Don't repeat yourself. Use best practice and good coding standards.`

(Using temp 0.8)

**Comment by liruiw** [comment]
same problem here. I am basically using llama recipe's quickstart for training and inference. Inference using the same prompt in this repo will work just fine.

**Comment by ArthurZucker** [comment]
Could you make sure you are using the latest release / main version of transformers?

**Comment by Regenhardt** [comment]
I'm actually using LlamaSharp (https://github.com/SciSharp/LLamaSharp) with the ggml model downloaded from TheBloke

**Comment by zaventh** [comment]
This issue still occurs with revision `4cb1403c377bb630ab92ec56272a6686c2bff315`  of `codellama/CodeLlama-13b-Instruct-hf` running on TGI.

**Comment by liruiw** [comment]
Actually this minimal example works fine on my computer now. A few references [1](https://huggingface.co/blog/codellama#transformers), [2](https://huggingface.co/spaces/codellama/codellama-playground), [3](https://huggingface.co/spaces/codellama/codellama-13b-chat/blob/main/model.py#L25).
```
from transformers import AutoTokenizer, LlamaForCausalLM
import transformers
import torch

model_id = "codellama/CodeLlama-7b-Instruct-hf"
tokenizer = AutoTokenizer.from_pretrained(model_id)

pipeline = transformers.pipeline(
    "text-generation",
    model="codellama/CodeLlama-7b-hf",
    torch_dtype=torch.float16,
    device_map="auto",
)

sequences = pipeline(
   'Write the code for quicksort.',
    do_sample=True,
    temperature=0.1,
    top_p=0.9,
    num_return_sequences=1,
    top_k=50,
    max_length=1024,
    eos_token_id=tokenizer.eos_token_id 
)
for seq in sequences:
    print(f"Result: {seq['generated_text']}")
```

**Comment by marco-ve** [comment]
After upgrading to the latest version of transformers (4.32.1) and huggingface_hub (0.16.4) with pip this gives me

`ValueError: Tokenizer class CodeLlamaTokenizer does not exist or is not currently imported.
`

**Comment by aliswel-mt** [comment]
Instead of act as padding, I faced all the output is new line
Not all the input act like this, but many of them just output a bunch of new line
ps. I am using latest version of transformers (4.32.1)

**Comment by ArthurZucker** [comment]
cc @marco-ve you should install main using `pip install git+https://github.com/huggingface/transformers`

**Comment by SerenNoble** [comment]
Has anyone solved the problem of generating a large number of line breaks?

**Comment by ArthurZucker** [comment]
You are most probably not using `main`.

**Comment by sootlasten** [comment]
@ArthurZucker is correct. The model repeating a token ad infinitum is the results of the `rope_theta` param not being read in correctly from the model params. This requires transformers version >= 4.33.0 (see also this thread: https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v1-GPTQ/discussions/2).

Closing this issue.
