### ISSUE TITLE
Run 13B or 34B in a single GPU

### ISSUE THREAD

**Issue by aliswel-mt** [meta-llama/codellama#27]
How to load 13B  or 34B in a single A100, I notice the model parallel size larger than 1 need more gpus

**Comment by GaganHonor** [comment]
[It is possible to run the 13B model on a single A100 GPU, which has sufficient VRAM](https://github.com/facebookresearch/llama/issues/186)[1](https://github.com/facebookresearch/llama/issues/186). However, it can be challenging to figure out how to get it working. [One user reported being able to run the 30B model on an A100 GPU using a specific setup](https://github.com/facebookresearch/llama/issues/186)[1](https://github.com/facebookresearch/llama/issues/186). [Another user reported being able to run the LLaMA-65B model on a single A100 80GB with 8-bit quantization](https://github.com/facebookresearch/llama/issues/101)[2](https://github.com/facebookresearch/llama/issues/101). You may want to refer to these examples and try similar approaches to see if they work for you. 

![NickYoungQuestionMarkGIF](https://github.com/facebookresearch/codellama/assets/141204441/c0ffc064-6e62-487e-a2c3-7a63b824dd80)

**Comment by manoj21192** [comment]
> How to load 13B or 34B in a single A100, I notice the model parallel size larger than 1 need more gpus

Hey, did you figure out how to load 13B model on single GPU in windows? I am also struggling with same issue.
