### ISSUE TITLE
NOTE: Redirects are currently not supported in Windows or MacOs.

### ISSUE THREAD

**Issue by Tu-Zhenzhao** [meta-llama/codellama#42]
Hi guys,

I am trying **CodeLlama-13b-Python** model in local MacOS 13.4.1 (c) M2, I can make sure I install all packages they need in `requirement.txt`. 

I want to make sure is it a setting up issue or we have to run this model on Linux, just want to make sure

**Comment by spmhickstein** [comment]
[https://github.com/facebookresearch/codellama/issues/32](url) same issue, I haven't tested yet, but sounds like a reasonable solution for Windows right now

**Comment by JadeCopet** [comment]
Duplicate of #32.
