### ISSUE TITLE
When running `bash download.sh` in my windows laptop, this happens

### ISSUE THREAD

**Issue by notTanveer** [meta-llama/codellama#44]
```command not found
download.sh: line 5: $'\r': command not found
': not a valid identifier: `PRESIGNED_URL

': not a valid identifier: `MODEL_SIZE
download.sh: line 12: $'\r': command not found
download.sh: line 22: syntax error near unexpected token `$'do\r''
'ownload.sh: line 22: `do```

**Comment by kalyniy** [comment]
You can try to install wsl (windows subsystem for linux) linux box and clone repository and run download.sh in there, and then just copy paste the files over. That's what I did yesterday, but I can't run torchrun command afterwards. I wasted my entire day yesterday. I installed ubuntu 22 and I never ran torchrun command successfully.

**Comment by capitanalegria** [comment]
The easiest way Ive been able to download all lama models in windows 10 is make sure you have wget and md5sums working on your windows machine, meaning the .exes are in the correct folders, md5sums.exe in the Windows folder and wget.exe in System32, and then double clicking on the download.bash ...make sure to download everything from secure places.

**Comment by shengbozeng** [comment]
Hi,do you run the shell script on the Windows OS? The script is based on Linux,but you are not perplex for this if you have git installed.

You can open the project folder by resources manager, select the folder and right click it,you can find "git bash here" item in menu, click it and you will get git terminal console.

And now try to run the download.sh in this terminal again.

**Comment by loleg** [comment]
I'm surprised the OP is even able to run `download.sh` without WSL.
Another good option is something like [Git for Windows](https://gitforwindows.org/).
This probably needs a README update, rather than code change.

**Comment by notTanveer** [comment]
> Hi,do you run the shell script on the Windows OS? The script is based on Linux,but you are not perplex for this if you have git installed.
> 
> You can open the project folder by resources manager, select the folder and right click it,you can find "git bash here" item in menu, click it and you will get git terminal console.
> 
> And now try to run the download.sh in this terminal again.

Thanks a lot, it worked. But now it shows that the wget and md5sums not found how do i fix this error. You are right I am running the script on Windows. If i need to change my system, guide me on how to do it. OR just tell me the process how you have done it or refer some yt. Thanks again.🙌

**Comment by loleg** [comment]
[Chocolatey](https://chocolatey.org/) is a good option for installing various utilities on Windows.

But as you will also need various Data Science components here, I suggest you follow the [PyTorch guide](https://pytorch.org/get-started/locally/#windows-anaconda) to get started on Windows with [Anaconda](https://anaconda.org/).

**Comment by colorincode** [comment]
I used conda (or mini conda it that's your vibe). I used anaconda/anaconda navigator. 
 
1) maybe not required but helped: Had to do a fresh Ubuntu install to avoid WSL interference. 
2) from anaconda interface click *cme.exe install* or just navigate to directory of your anaconda install, you'll need to use terminal/bash from there.
3) You *must* run through conda activate and conda init for conda to run bash, without modifying path vars. This enabled me to call bash scripts from the anaconda CMD prompt.

**Comment by shengbozeng** [comment]
> > Hi,do you run the shell script on the Windows OS? The script is based on Linux,but you are not perplex for this if you have git installed.
> 
> > 
> 
> > You can open the project folder by resources manager, select the folder and right click it,you can find "git bash here" item in menu, click it and you will get git terminal console.
> 
> > 
> 
> > And now try to run the download.sh in this terminal again.
> 
> 
> 
> Thanks a lot, it worked. But now it shows that the wget and md5sums not found how do i fix this error. You are right I am running the script on Windows. If i need to change my system, guide me on how to do it. OR just tell me the process how you have done it or refer some yt. Thanks again.🙌

Wget and md5sums are commands in Linux, and they should be installed in git terminal.

If you can't found them,I think that must be you did not select some options when you installed git.

Sometimes, reinstalling Git for Windows with additional options checked (like “Use Unix tools from the Windows Command Prompt”) might include more utilities.

It's maybe fix the issue.

**Comment by mhamra** [comment]
I used the download.sh script in WSL2, and after that, I moved the files to another location. The command `explorer.exe .` in the wsl2 directory opens the Windows Explorer application and allows copy/paste operations on files. I've moved all the downloaded folders inside the `codellama` directory in Windows, where I've cloned the repository to run the examples.

Is that ok? I have problems running the examples in Windows 10 (see this issue #55)

**Comment by notTanveer** [comment]
> > > Hi,do you run the shell script on the Windows OS? The script is based on Linux,but you are not perplex for this if you have git installed.
> > 
> > 
> > > 
> > 
> > 
> > > You can open the project folder by resources manager, select the folder and right click it,you can find "git bash here" item in menu, click it and you will get git terminal console.
> > 
> > 
> > > 
> > 
> > 
> > > And now try to run the download.sh in this terminal again.
> > 
> > 
> > Thanks a lot, it worked. But now it shows that the wget and md5sums not found how do i fix this error. You are right I am running the script on Windows. If i need to change my system, guide me on how to do it. OR just tell me the process how you have done it or refer some yt. Thanks again.🙌
> 
> Wget and md5sums are commands in Linux, and they should be installed in git terminal.
> 
> If you can't found them,I think that must be you did not select some options when you installed git.
> 
> Sometimes, reinstalling Git for Windows with additional options checked (like “Use Unix tools from the Windows Command Prompt”) might include more utilities.
> 
> It's maybe fix the issue.

I tried that process but it doesnt seem to be working. If you guys can tell me the step by step process on how you have done it will help me a lot.(Windows user)

**Comment by shengbozeng** [comment]
> 

step1: please visit https://git-scm.com/download/win , and download correct version for windows;
step2: run the setup file of git, and follow tips;
step3: 
![image](https://github.com/facebookresearch/codellama/assets/53858417/d31bbfb3-10f6-42c1-bcd9-d35758abd4e1)
 
step4: click 'next' button and setup;
step5: done.

**Comment by shengbozeng** [comment]
> > > > Hi,do you run the shell script on the Windows OS? The script is based on Linux,but you are not perplex for this if you have git installed.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > You can open the project folder by resources manager, select the folder and right click it,you can find "git bash here" item in menu, click it and you will get git terminal console.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > And now try to run the download.sh in this terminal again.
> > > 
> > > 
> > > Thanks a lot, it worked. But now it shows that the wget and md5sums not found how do i fix this error. You are right I am running the script on Windows. If i need to change my system, guide me on how to do it. OR just tell me the process how you have done it or refer some yt. Thanks again.🙌
> > 
> > 
> > Wget and md5sums are commands in Linux, and they should be installed in git terminal.
> > If you can't found them,I think that must be you did not select some options when you installed git.
> > Sometimes, reinstalling Git for Windows with additional options checked (like “Use Unix tools from the Windows Command Prompt”) might include more utilities.
> > It's maybe fix the issue.
> 
> I tried that process but it doesnt seem to be working. If you guys can tell me the step by step process on how you have done it will help me a lot.(Windows user)

step1: please visit https://git-scm.com/download/win , and download correct version for windows;
step2: run the setup file of git, and follow tips;
step3:
![image](https://github.com/facebookresearch/codellama/assets/53858417/8174b83c-6c2f-4732-800b-d72a46e10399)

step4: click 'next' button and setup;
step5: done.

**Comment by notTanveer** [comment]
Help me with this, from where do i install wget and md5sum

**Comment by monstorbak** [comment]
I struggled with this as well. I successfully ran download.sh on a Windows 11 laptop using git for Windows, then I could not replicate the process on another PC. The fix for me was to reinstall git for Windows on the second PC for the **64-bit version of git** as opposed to the 32-bit version that was previously running (and failing).
