### ISSUE TITLE
access through HuggingFace?

### ISSUE THREAD

**Issue by i-am-neo** [meta-llama/codellama#5]
Thanks so much for your work and for opening up access to Code Llama.

We received access for Llama2 previously and access the models via HF.  Is it possible to do the same with Code Llama?
(We just requested access for Code Llama via your submission form).

**Comment by dennis-gonzales** [comment]
+1

**Comment by timxx** [comment]
Maybe https://huggingface.co/codellama is the official HF?

**Comment by GaganHonor** [comment]
https://huggingface.co/blog/codellama#conversational-instructions lol 💀

**Comment by ryancurrah** [comment]
What's benefit of using huggingface vs just downloading it?

**Comment by lostmygithubaccount** [comment]
> What's benefit of using huggingface vs just downloading it?

a free layer of abstraction

**Comment by GaganHonor** [comment]
> What's benefit of using huggingface vs just downloading it?

Same as using Bing Chat vs Chat GPT4 by open Ai

**Comment by varunk29** [comment]
Hugging face version seems to run very slow, is it only me ?

**Comment by timxx** [comment]
> Hugging face version seems to run very slow, is it only me ?

I have the same problem with 7b instruct hf model.

**Comment by syhw** [comment]
Here are some links:
[Models on the Hub](https://huggingface.co/codellama)
[Demo (code completion, streaming server)](https://huggingface.co/spaces/codellama/codellama-playground)
[Demo (instruction fine-tuned, self-contained & clonable)](https://huggingface.co/spaces/codellama/codellama-13b-chat)
