### ISSUE TITLE
Programming Languages Support

### ISSUE THREAD

**Issue by rahuldshetty** [meta-llama/codellama#53]
Is there any chart or breakdown of % programming languages used in training data for the base/instruct models?

**Comment by syhw** [comment]
There is no exhaustive list, and you should try your favorite language. There should at least be those languages: "assembly", "batchfile", "c++", "c", "c-sharp", "cmake", "css", "dockerfile", "fortran", "go", "haskell", "html", "java",
"javascript", "julia", "lua", "makefile", "markdown", "perl", "php", "powershell", "python", "ruby", "rust", 
"scala", "shell", "sql", "tex", "visual-basic".
