### ISSUE TITLE
Size of the model info is missing

### ISSUE THREAD

**Issue by suyashcjoshi** [meta-llama/codellama#6]
It would be helpful to mention the size of disk space the pre-trained models will take so as to determine if this can be easily done on laptop or not.

**Comment by Hangsiin** [comment]
I downloaded 7B-Python version and it was 12.55GB.

**Comment by Rupesh-rkgit** [comment]
13B is 24GB approx

**Comment by jspisak** [comment]
I can put up a PR and add a table to the readme. I agree this is a handy thing to have..

**Comment by jspisak** [comment]
https://github.com/facebookresearch/codellama/pull/103

Closing this issue as I'll merge it to the readme this morning. Thanks!
