### ISSUE TITLE
unable to download the model weights

### ISSUE THREAD

**Issue by vshanyiao** [meta-llama/codellama#61]
I was unable to download the authorized model within the 24-hour timeframe specified in the authorization email.

--2023-08-29 22:06:38--  https://download2.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaX......Request-ID=724013916200119
Resolving download2.llamameta.net (download2.llamameta.net)... 99.84.133.49, 99.84.133.23, 99.84.133.48, ...
Connecting to download2.llamameta.net (download2.llamameta.net)|99.84.133.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7020 (6.9K) [binary/octet-stream]
Saving to: './LICENSE'

./LICENSE                                           100%[===================================================================================================================>]   6.86K  --.-KB/s    in 0s      

2023-08-29 22:06:39 (163 MB/s) - './LICENSE' saved [7020/7020]

--2023-08-29 22:06:39--  https://download2.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaX......&Request-ID=724013916200119
Resolving download2.llamameta.net (download2.llamameta.net)... 99.84.133.49, 99.84.133.23, 99.84.133.48, ...
Connecting to download2.llamameta.net (download2.llamameta.net)|99.84.133.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4790 (4.7K) [text/markdown]
Saving to: './USE_POLICY.md'

./USE_POLICY.md                                     100%[===================================================================================================================>]   4.68K  --.-KB/s    in 0s      

2023-08-29 22:06:39 (139 MB/s) - './USE_POLICY.md' saved [4790/4790]

Downloading tokenizer
--2023-08-29 22:06:39--  https://download2.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaX......&Request-ID=724013916200119
Resolving download2.llamameta.net (download2.llamameta.net)... 99.84.133.49, 99.84.133.23, 99.84.133.48, ...
Connecting to download2.llamameta.net (download2.llamameta.net)|99.84.133.49|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-08-29 22:06:41 ERROR 403: Forbidden.

--2023-08-29 22:06:41--  https://download2.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaX......&Request-ID=724013916200119
Reusing existing connection to download2.llamameta.net:443.
HTTP request sent, awaiting response... 403 Forbidden
2023-08-29 22:06:41 ERROR 403: Forbidden.

**Comment by GaganHonor** [comment]
Did you used the Download URL within 24 hours ?

**Comment by freesky-edward** [comment]
I got the same message, I am sure it within 24 hours, are there any other restrictions?

**Comment by freesky-edward** [comment]
Everything works fine after applying again

**Comment by jspisak** [comment]
Can we close this issue? Seems like @samuelselvan we should document this somewhere?

**Comment by GaganHonor** [comment]
yes close this issue :) 
![CommitPoliceCommitGIF](https://github.com/facebookresearch/codellama/assets/141204441/58496352-01fe-4bc8-a60a-aa9005e5addc)

**Comment by jspisak** [comment]
roger that!

**Comment by Soumendraprasad** [comment]
@jspisak , @freesky-edward , @vshanyiao  , I am also facing the same . I am trying to download it just after getting the permission mail , but the same is showing . Could you guide to how to resolve this .  This issue is exactly same as @vshanyiao ones .


Connecting to download2.llamameta.net (download2.llamameta.net)|18.67.195.80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-10-25 06:27:16 ERROR 403: Forbidden.
