### ISSUE TITLE
how to install wget and md5sum.(Windows user)

### ISSUE THREAD

**Issue by notTanveer** [meta-llama/codellama#66]
I am running all the commands in a git bash terminal.
If you guys tell me a step by step method on how to install the model it will be very helpful

```download.sh: line 18: wget: command not found
download.sh: line 19: wget: command not found
Downloading CodeLlama-7b
download.sh: line 53: wget: command not found
download.sh: line 56: wget: command not found
download.sh: line 57: wget: command not found
download.sh: line 58: wget: command not found
Checking checksums
md5sum: checklist.chk: No such file or directory```

**Comment by bank010** [comment]
https://eternallybored.org/misc/wget/1.21.4/32/wget.exe
下载后放入Git/mingw64/bin文件下就可以用wget命令

**Comment by notTanveer** [comment]
> https://eternallybored.org/misc/wget/1.21.4/32/wget.exe
> 下载后放入Git/mingw64/bin文件下就可以用wget命令

Still doesnt work. Is there any specific path where i need to store the .exe file? 
How to install md5sums

**Comment by syhw** [comment]
You can use WSL https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by GaganHonor** [comment]
WSL ( Windows Subsystem for Linux ╰(*°▽°*)╯) is best option for Windows users ( I am on W11 ) 
I suggest to use WSL2 as it's best for [codellama](https://github.com/facebookresearch/codellama/)

Enable It ✅
To install WSL 2 on Windows 11 by PowerShell, follow these steps:

1. Open PowerShell as administrator.
2. Run the command: `wsl --install`
3. Restart your PC.
4. To verify that WSL 2 is installed, run the command: `wsl --set-default-version 2`
5. To check the version of your Linux distribution, run the command: `wsl -l -v`

For more details, you can refer to these sources:

- (How to Install WSL2 on Windows 10 and Windows 11 - https://petri.com/install-wsl2-windows/
- (Install WSL | Microsoft Learn - https://learn.microsoft.com/en-us/windows/wsl/install 


![Screenshot 2023-08-31 093642](https://github.com/facebookresearch/codellama/assets/141204441/f8555dec-86e1-41f3-ad40-b1776512d840)
![Screenshot 2023-08-31 093511](https://github.com/facebookresearch/codellama/assets/141204441/ca4e24d5-ee85-40f0-9de9-a2fd1745e9c5)


you can also enable the feature manually - ` dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart` and  `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`


after installation successfully 
![Screenshot 2023-08-31 104122](https://github.com/facebookresearch/codellama/assets/141204441/778397ef-f69a-4d87-970a-376f7b2e2ad9)
more help 👍  https://devblogs.microsoft.com/commandline/install-wsl-with-a-single-command-now-available-in-windows-10-version-2004-and-higher/

and yes after login use `sudo apt install coreutils` and ` sudo apt install wget`
and please ask more if need help as i myself using WSL method. 🤖

**Comment by broken-bytes** [comment]
Was about to mention WSL as well, got it working there but chat is rather slow. Taking around 60s to respond for 1024 max size.

i7 12700K
64GB RAM
RTX 4080

Should be way faster than that imho.

**Comment by tantravahi-kalyan** [comment]
Hello @notTanveer I'm having the same issue, can you please send a detailed note on how to download codellama in my local and run the download.sh file.

./download.sh: line 18: wget: command not found
./download.sh: line 19: wget: command not found
Downloading CodeLlama-7b
./download.sh: line 59: wget: command not found
./download.sh: line 62: wget: command not found
./download.sh: line 63: wget: command not found
./download.sh: line 64: wget: command not found
Checking checksums
md5sum: checklist.chk: No such file or directory

Thankyou

**Comment by notTanveer** [comment]
> Hello @notTanveer I'm having the same issue, can you please send a detailed note on how to download codellama in my local and run the download.sh file.
> 
> ./download.sh: line 18: wget: command not found
> ./download.sh: line 19: wget: command not found
> Downloading CodeLlama-7b
> ./download.sh: line 59: wget: command not found
> ./download.sh: line 62: wget: command not found
> ./download.sh: line 63: wget: command not found
> ./download.sh: line 64: wget: command not found
> Checking checksums
> md5sum: checklist.chk: No such file or directory
> 
> Thankyou
> 

Switch to WSL.

**Comment by spikers** [comment]
>I'm having the same issue, can you please send a detailed note on how to download codellama in my local and run the download.sh file.

WSL should have wget and md5. https://github.com/meta-llama/codellama/issues/66#issuecomment-1700370515 tells you how to download it. If you're on Windows and you have wsl installed, to see which ones are available for download, use this command: `wsl -l -o` You should get a list like this:
```
NAME                                   FRIENDLY NAME
Ubuntu                                 Ubuntu
Debian                                 Debian GNU/Linux
kali-linux                             Kali Linux Rolling
Ubuntu-18.04                           Ubuntu 18.04 LTS
Ubuntu-20.04                           Ubuntu 20.04 LTS
Ubuntu-22.04                           Ubuntu 22.04 LTS
```

I used this one: `wsl --install -d Ubuntu-22.04`

The username/password is kind of arbitrary, so I set up my username to be
User: myname
Pass: mypw

You should be logged in. See the end to see if you're not immediately logged in. Note: WSL will automatically open to your current directory. 

You should get a shell that looks like this, ensure it's the same directory as your llama3 repo with the download.sh. If it isn't, go find it:
`myname@COMPUTERNAME-ABC123:/mnt/c/llama3$`

In the above example, my llama3 is inside `C:/llama3`, but it shows up as `/mnt/c/llama3/`

If you found it, run: `./download.sh`
It asks for the link you got. It should be like: `https://download6.llamameta.net/*?` then other stuff. It's like 600-700 chars long (mine is 687). Paste that in and press enter. 
Then it asks for which models you want, I typed: `8B,8B-instruct`
It should start downloading at this point. Mine looked like this while it downloaded: `./Meta-Llama-3-8B/consolidated.00  68%[=======================================>                   ]  10.18G  16.7MB/s    eta 5m 24s`
Good luck!


### If you aren't immediately logged in (or if you're logged out), do this:
Run `wsl -l -v` to see which distros you have on your machine. I got this:
`Ubuntu-22.04           Stopped         2`

Run this to run WSL with the Ubuntu-22.04 distro: `wsl --distribution Ubuntu-22.04`

Then go to the llama3 folder and run `./download.sh` and follow the instructions from there. 

### Other Errors:
If you get 403 Forbidden, you need to re-request a link. You might get approved immediately. Note: I failed to download it 5x in a row and I had to re-request a link. 

If you get some error that say something like "out of specified range", go into download.sh and remove all the `--continue`
  *  For example: Line 19 goes from: `wget --continue ${PRESIGNED_URL/'*'/"LICENSE"} -O ${TARGET_FOLDER}"/LICENSE"` to `wget ${PRESIGNED_URL/'*'/"LICENSE"} -O ${TARGET_FOLDER}"/LICENSE"`
  *  There's 6x `--continue` in the file

If you get some weird bash errors, make sure you installed an ubuntu version.
  *  I remember I did some weird stuff that didn't work. One thing I did was change the first line to replace "bash" with "sh", then it gave a sequence error, so I changed the sequence line to be like seq -w 00 0 ${SHARD}, it looked like it was doing something, but like I said, that stuff didn't actually download for me.
