### ISSUE TITLE
Sponsored issue: I need it for my project

### ISSUE THREAD

**Issue by APMNoman** [meta-llama/codellama#67]
## Priority Support

- @apmnoman is using  [Mintycode](https://mintycode.io) to fund this issue.
- You can receive ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) if you provide priority support to @apmnoman. 
- To view the support request and terms go to  [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=34e64f65-9635-4d16-97c3-30cfbbe8e21c&owner=facebookresearch&name=codellama).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by GaganHonor** [comment]
Just read 📖 me or ask Questions
