### ISSUE TITLE
Where is the 70B Model?

### ISSUE THREAD

**Issue by shroominic** [meta-llama/codellama#7]
Just a question: Are you planning to release the 70B model in the future or what is the plan?

**Comment by syhw** [comment]
No plans to release a 70B Code Llama model as of now.

**Comment by sirus20x6** [comment]
I think we'd appreciate it if it exists. Hardware is getting better. Inference is getting optimized. people are buying new gpus and ram just for LLMs. Hell I bought an Epyc system with 512gb of ram for this stuff. So far I'm still shackled to chatgpt4, and as much as I like it, there are some things I would like to keep in house. Also if I start building apps with the api it would get really expensive really quick. I feel like llama2 and codellama are close to greatness, but there is only so far finetuning can bring us.

**Comment by ignoramous** [comment]
Announced today: https://analyticsindiamag.com/meta-releases-code-llama-70b/

**Comment by mayurtikundi12** [comment]
Announced today: https://bizmorphic.com/blogs/meta-ais-massive-70b-parameter-codex-crushes-gpt-and-googles-gemini-models
