### ISSUE TITLE
Can codellama achieve what it claims on HumanEval?

### ISSUE THREAD

**Issue by jybbjybb** [meta-llama/codellama#72]
I used codellama python 7B  to generate code for human eval dataset (164 questions). I can only get 3 or 4 problems correct, much worse than codellama claims (38%). Is there any trick to make it work? I use the default setting in example_completion.py.

One of the problem that all llama faces is it does not know when to stop. The first few line of codes seems correct. Then it generates non-related codes. 

Can someone show their codes to use codellama to reproduce the human eval results? Thank you!

**Comment by GaganHonor** [comment]
train it! 
![IMessedUpMyBadGIF](https://github.com/facebookresearch/codellama/assets/141204441/4c840e8d-03a4-4fcd-a327-db4aaff262dd)

**Comment by jgehring** [comment]
Hi @jybbjybb, in our evaluations we truncate the generations based on custom stop words. See [the HumanEval implementation in the BigCode evaluation harness](https://github.com/bigcode-project/bigcode-evaluation-harness/blob/136b93c0aea40652b8494bb0df93125b2ea1f833/lm_eval/tasks/humaneval.py#L54) for an example of stop words for this task.

Feel free to re-open this issue if you have further questions on this.

**Comment by nicoladainese96** [comment]
Hi @jgehring what about batched generations with these models? Is there an official way to deal with padding?

**Comment by mu-arkhipov** [comment]
@jgehring 
> we truncate the generations based on custom stop words
> See [the HumanEval implementation in the BigCode evaluation harness](https://github.com/bigcode-project/bigcode-evaluation-harness/blob/136b93c0aea40652b8494bb0df93125b2ea1f833/lm_eval/tasks/humaneval.py#L54) for an example of stop words for this task.

Do you use the same stop words as `bigcode-evaluation-harness`? If no, can you publish your custom stopwords?
