### ISSUE TITLE
Hardware requirement for 100K tokens

### ISSUE THREAD

**Issue by dittops** [meta-llama/codellama#75]
What hardware is required to run the 34B Instruct model with 100K context length?

**Comment by Kushalamummigatti** [comment]
@dittops were you able to solve this? And where is the change need to be done for 100k length.

**Comment by jgehring** [comment]
Hi @dittops, in our experiments we used 4 A100s. However, the codellama code-base provides a clean reference implementation and is hence intentionally lacking speed and memory optimizations. As such, attempting to use 100k tokens of context on 4 A100s will produce out-of-memory errors.

I would suggest looking into other inference code-bases utilizing [xformers](https://github.com/facebookresearch/xformers), HuggingFace's [Accelerate](https://huggingface.co/docs/accelerate/index) library, or software packages that offer quantized models.

Feel free to re-open the issue if you have further questions.
