### ISSUE TITLE
Display of additional vague comments once code is generated

### ISSUE THREAD

**Issue by manoj21192** [meta-llama/codellama#76]
I am using a CodeLlama-7b model to generate a code. I provided the following prompt , "prompts=["Write a function in python to add two numbers and return their sum"] and got the below output.
Can someone explain why it is showing additional vague comments once code is generated and how to make sure these are not generated along with code?
![Capture](https://github.com/facebookresearch/codellama/assets/52530801/074df101-6809-4734-b62f-cee7743e6bdb)

**Comment by AdarshAcharya5** [comment]
Have you tried running it multiple times?. Has it happened again or just this once?

**Comment by GaganHonor** [comment]
To reduce or eliminate such comments in the generated code, you can try the following steps:

**Prompt Refinement:** Make your prompt more specific and explicit. Clearly state that you only want the model to generate the code and exclude any additional comments. For example, you can modify your prompt to: "Write a Python function called add that takes two numbers as input and returns their sum."

**Post-processing:** After generating the code, you can apply post-processing techniques to filter out the additional comments. You can use regular expressions or string matching to identify and remove the unwanted comments from the generated output.

**Model Fine-tuning:** If you have access to the model's training pipeline, you can consider fine-tuning the model on a dataset that specifically focuses on generating code without comments. By training the model on such data, it can learn to generate code outputs that are more aligned with your requirements.

**Comment by manoj21192** [comment]
@AdarshAcharya5 : Yes, comments appearing everytime code is run.
@GaganHonor : My prompt was already very specific, slightly modifying the prompt to what you mentioned above, is giving erroneous results (not even generating the code), please refer below snapshot. 
![Error1](https://github.com/facebookresearch/codellama/assets/52530801/e1fa2753-7fc4-4e4c-a00b-adf408965a75)

**Comment by manoj21192** [comment]
It worked, I was running the codellama-7b and not the Instruct version, hence these comments were being generated.

**Comment by GaganHonor** [comment]
Congratulations 🎊  Sorry i wasn't much help , keep growing 😊
