### ISSUE TITLE
Error when requesting a download link

### ISSUE THREAD

**Issue by LakoMoor** [meta-llama/codellama#80]
I received this email:

Sorry, you are not eligible to access Llama 2.

Thank you for your interest in using Llama 2. Unfortunately, you do not meet the criteria to obtain a license at this time.

**Comment by GaganHonor** [comment]
something is wrong!
see this image : https://github.com/GaganHonor/codellama-gagan-singh/blob/main/media/MAILDEMO.jpg

I request you to follow readme.md correctly and try again :)

**Comment by LakoMoor** [comment]
> something is wrong! see this image : https://github.com/GaganHonor/codellama-gagan-singh/blob/main/media/MAILDEMO.jpg
> 
> I request you to follow readme.md correctly and try again :)

in readme.md i see only:
In order to download the model weights and tokenizers, please visit the [Meta AI website](https://ai.meta.com/resources/models-and-libraries/llama-downloads/) and accept our License.

**Comment by GaganHonor** [comment]
re fill this form with new id & check if country is not restricted ? If specific error share logs here 😊

**Comment by LakoMoor** [comment]
> re fill this form with new id & check if country is not restricted ? If specific error share logs here 😊

i try my country and  U.S. I also tried different emails. The rejection is the same.(((

**Comment by LakoMoor** [comment]
![image](https://github.com/facebookresearch/codellama/assets/44299427/9a9914c0-6598-4038-9c9d-c1f01972fff8)

**Comment by GaganHonor** [comment]
hmmmm , Ok I request you to use a new device and your real email id provided by Gmail or outlook etc. , That's only possible solution , U.S is not restricted  . Thanks , Let me know further

**Comment by LakoMoor** [comment]
> hmmmm , Ok I request you to use a new device and your real email id provided by Gmail or outlook etc. , That's only possible solution , U.S is not restricted . Thanks , Let me know further

I have already tried using the phone, my work laptop, and even tried through the server. I also used Gmail and my work email :D

**Comment by LakoMoor** [comment]
Ok, I bought a server in the USA. Through him I tried to fill out a questionnaire. I received a message with the url :) Thank you for everything)

**Comment by GaganHonor** [comment]
You mean RDP ? Virtual machine ?

**Comment by LakoMoor** [comment]
> You mean RDP ? Virtual machine ?

Yep. VPS server

**Comment by GaganHonor** [comment]
strange that you have to use VPS for this  still congrats :)

**Comment by zoujiulong** [comment]
I meet same problem，how to solve

**Comment by GaganHonor** [comment]
> I meet same problem，how to solve

Try buying a VPS , and your server loaction should be USA and that's all , you can use AWS Free Tier , Azure Free server
