### ISSUE TITLE
Bash .sh vs Bin .zsh Mac OS

### ISSUE THREAD

**Issue by artcore-c** [meta-llama/codellama#81]
I have installed wget and md5sha1sum using Macports and created a directory (folder) for this project by typing

"mkdir ~/CodeLlama-git"

and then

"cd ~/CodeLlama-git"

which brings my terminal to the new folder, but I'm using .zsh not .sh as my shell, most Macs do this, the point being bash can work on a Mac but I have my terminal set up and working well (I have multiple projects...) so I'm wondering what would be the next command to download Llama into my newly created directory. I don't want to use bash and end up with Llama as the only project I'm able to work with after converting from .zsh to .sh, I know there's a conversion that can make this a simple task...
maybe someone has the answer?

**Comment by artcore-c** [comment]
I ask Code Llama what to do and got this...

 To convert a Bash shell script to a Z Shell (ZSH) script, you can follow these steps:

1. Open the original Bash script in a plain text editor like Notepad or TextEdit.
2. Replace all instances of `bash` at the beginning of each line with `#!/bin/zsh`. This tells the operating system to run the script using the ZSH interpreter.
3. Remove any lines that begin with `source`, since they are specific to Bash and do not apply to ZSH.
4. Change any references to the `$BASH_SOURCE` environment variable to `${(%):-%N}`. This variable contains the full pathname of the current script file in ZSH, similar to how `$BASH_SOURCE` works in Bash.
5. Check for any other Bash-specific features or commands that may not work correctly in ZSH, and modify them accordingly.
6. Save the modified script with a `.zsh` extension, making sure to preserve the same permissions and ownership as the original script.
7. Make the script executable by running `chmod +x /path/to/script.zsh`.
8. Run the script by typing `/path/to/script.zsh` followed by any arguments or options required.

Note that converting a Bash script to ZSH may involve more than just replacing `bash` with `#!/bin/zsh` at the top of the script. Depending on the complexity of the script, you may need to make changes throughout the code to accommodate differences between the two shells.

Can anyone confirm this is correct? I use bin not bash so it looks like it might work, but it seems overly complex, I guess I'll try... the original argument is ```bash download.sh```, surely this has a simpler conversion than what CL suggests?

**Comment by artcore-c** [comment]
I rephrased the question, since I've already created the directory I think I just add curl before the URL...
 
 To convert the `download.sh` command to work with a Z Shell (ZSH) terminal, you can replace the `bash` shebang (`#!/bin/bash`) with the equivalent ZSH shebang (`#!/usr/local/bin/zsh`). Here's an example of how the updated script might look:
```zsh
#!/usr/local/bin/zsh

# Download a file from the internet
curl -O https://example.com/file.txt
```
Alternatively, if you want to continue using the `bash` shebang but still make the script compatible with both `bash` and `zsh`, you can add the `-l` option after the shebang, like this:
```bash
#!/bin/bash -l

# Download a file from the internet
curl -O https://example.com/file.txt
```
The `-l` option tells `bash` to behave more like `zsh` when interpreting the script, which can help avoid compatibility issues.

**Comment by artcore-c** [comment]
No that didn't work, copy/pasta my terminal output below...


❯ cd ~/CodeLlama-git

❯ curl https://download2.llamameta.net/\*\?Policy\=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiYnp1ZmZjcGlqZWVvN29pcTZ5enFrdXk1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQyLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTM3NjIzOTJ9fX1dfQ__\&Signature\=qRypH23MgwW25RT26Ews8xZIXT2sDg6KnAmlyToba7p31BxnBTM3aht%7Ez2L9Mrzu8RVLz0My--7J3mAzf1TJzwZNE-8VMARvTA%7EoD-LGXxjwM8cJA47ay%7Ey3gFk7FgT0MStEkKnpTpED1GoJuGyu47TQqDsgkoV0wO%7EqnmLictV40oXfTkXEE0Sn68CAnh0AlGk4SL33l7OII6VsxDYSqV7ueZgOnLmtbT1wsxlKxNJzErme4Vp3Xc%7EXGwaoRDTcpRjkkVi7CUxzjhqsLb%7E7nXC5o6llAR33GujRuppEnLQy04dkuYrbY4QsPLQui1J38rLSCr7jfpLJi2Oqv3wgbw__\&Key-Pair-Id\=K15QRJLYKIFSLZ\&Download-Request-ID\=2897926777036283

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Detected User-agent is not wget cloudfront-check-download-url</title>
</head>
<body>
    <p>Please follow the instructions on our <a href="https://github.com/facebookresearch/codellama">Code Llama GitHub repository</a> page to access the Code Llama model downloads.</p>
    <p>Github <a href="https://github.com/facebookresearch/codellama/blob/main/README.md">README</a></p>
    <p>Github <a href="https://github.com/facebookresearch/codellama/blob/main/download.sh">download.sh</a></p>
</body>
</html>

**Comment by artcore-c** [comment]
Can't I just clone the repository like any normal git download?

**Comment by artcore-c** [comment]
Rephrased the question again... we shall see?


 To download the Code Llama model using a Mac with a Z-shell terminal, you can follow these steps:

1. First, open the Terminal app on your Mac.
2. Navigate to the directory where you want to save the downloaded files. For example, if you want to save the files in a directory called `CodeLlama-git` inside your home folder, you can type `cd ~/CodeLlama-git` and press Enter.
3. Next, enter the following command to download the Code Llama model:
```bash
wget --no-check-certificate \
     --content-disposition \
     --directory-prefix=./ \
     https://dl.fbaipublicfiles.com/codella/model.tar.gz
```
This will download the Code Llama model archive file named `model.tar.gz` into the current working directory.
4. Once the download is complete, extract the contents of the archive file by entering the following command:
```bash
tar xvf model.tar.gz
```
This will create a new subdirectory called `model` containing the extracted files.
5. Finally, navigate to the newly created `model` subdirectory and verify that the downloaded files are present by listing the contents of the directory:
```bash
ls -la
```
This should show you the list of files and directories contained within the `model` subdirectory.

That's it! You should now have successfully downloaded the Code Llama model onto your Mac using the Z-shell terminal.

**Comment by artcore-c** [comment]
Well at least I got an error 403 forbidden, it looks like I'm getting somewhere anyway...

my terminal output below after following the above (from Perplexity Labs) Code Llama's advice:

❯ wget --no-check-certificate \
     --content-disposition \
     --directory-prefix=./ \
     https://dl.fbaipublicfiles.com/codella/model.tar.gz
--2023-09-02 19:28:20--  https://dl.fbaipublicfiles.com/codella/model.tar.gz
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 2600:9000:2353:3400:13:6e38:acc0:93a1, 2600:9000:2353:c600:13:6e38:acc0:93a1, 2600:9000:2353:8400:13:6e38:acc0:93a1, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|2600:9000:2353:3400:13:6e38:acc0:93a1|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-09-02 19:28:20 ERROR 403: Forbidden.

**Comment by artcore-c** [comment]
and with just ```wget```

❯ wget https://download2.llamameta.net/\*\?Policy\=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiYnp1ZmZjcGlqZWVvN29pcTZ5enFrdXk1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQyLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTM3NjIzOTJ9fX1dfQ__\&Signature\=qRypH23MgwW25RT26Ews8xZIXT2sDg6KnAmlyToba7p31BxnBTM3aht%7Ez2L9Mrzu8RVLz0My--7J3mAzf1TJzwZNE-8VMARvTA%7EoD-LGXxjwM8cJA47ay%7Ey3gFk7FgT0MStEkKnpTpED1GoJuGyu47TQqDsgkoV0wO%7EqnmLictV40oXfTkXEE0Sn68CAnh0AlGk4SL33l7OII6VsxDYSqV7ueZgOnLmtbT1wsxlKxNJzErme4Vp3Xc%7EXGwaoRDTcpRjkkVi7CUxzjhqsLb%7E7nXC5o6llAR33GujRuppEnLQy04dkuYrbY4QsPLQui1J38rLSCr7jfpLJi2Oqv3wgbw__\&Key-Pair-Id\=K15QRJLYKIFSLZ\&Download-Request-ID\=2897926777036283
Warning: wildcards not supported in HTTP.
The destination name is too long (652), reducing to 236
--2023-09-02 19:34:29--  https://download2.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiYnp1ZmZjcGlqZWVvN29pcTZ5enFrdXk1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQyLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTM3NjIzOTJ9fX1dfQ__&Signature=qRypH23MgwW25RT26Ews8xZIXT2sDg6KnAmlyToba7p31BxnBTM3aht%7Ez2L9Mrzu8RVLz0My--7J3mAzf1TJzwZNE-8VMARvTA%7EoD-LGXxjwM8cJA47ay%7Ey3gFk7FgT0MStEkKnpTpED1GoJuGyu47TQqDsgkoV0wO%7EqnmLictV40oXfTkXEE0Sn68CAnh0AlGk4SL33l7OII6VsxDYSqV7ueZgOnLmtbT1wsxlKxNJzErme4Vp3Xc%7EXGwaoRDTcpRjkkVi7CUxzjhqsLb%7E7nXC5o6llAR33GujRuppEnLQy04dkuYrbY4QsPLQui1J38rLSCr7jfpLJi2Oqv3wgbw__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=2897926777036283
Resolving download2.llamameta.net (download2.llamameta.net)... 2607:7700:0:10:0:2:6c9d:a261, 2607:7700:0:10:0:2:6c9d:a248, 2607:7700:0:10:0:2:6c9d:a27a, ...
Connecting to download2.llamameta.net (download2.llamameta.net)|2607:7700:0:10:0:2:6c9d:a261|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-09-02 19:34:30 ERROR 403: Forbidden.

**Comment by artcore-c** [comment]
OMG! so simple I just cloned the repo from the github page, hrmmm, must be something I'm missing? 
oh yeah the tokens, well I give up, for now anyway.

my terminal:

❯ git clone https://github.com/facebookresearch/codellama.git
Cloning into 'codellama'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 30 (delta 6), reused 4 (delta 4), pack-reused 15
Receiving objects: 100% (30/30), 21.95 KiB | 702.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.

**Comment by GaganHonor** [comment]
:shipit: By any chance is this your first time :trollface:

**Comment by artcore-c** [comment]
> :shipit: By any chance is this your first time :trollface:

no, but I'm not an expert, my experience has been mostly with Raspberry pi OS and Mac OS, I've built some Web UI with React, and compile my own Blender app from daily source (I'm much better at 3D modeling 🤨). I'm sure I could get it to work strictly following the directions using bash with .sh, I just want it to work with .zsh, and downloaded to my folder of choice... I've blindly followed things like this in the past and had problems with paths getting all messed up. I just don't understand why the whole long URL token thing for version downloads, couldn't they just be listed where we could select what we want without all the fuss?

**Comment by artcore-c** [comment]
btw this particular code, and llm in general are yeah maybe new to me, but I've been collecting books and publications about AI (and robotics...) for the last 40 some years. to me this is just the current hype, again, and it will pass, just as before, every time it passes. after the money goes in and doesn't see a return anyway, that's usually the case. see any honda asimo running around yet, exactly... anyway, I was interested in messing about with it to see what I could come up with, nothing too serious just for fun.

**Comment by artcore-c** [comment]
I'm interested in modeling the Claustrum network with asynchronous switching in c#, among other things, I might not be keen on the current syntax of this project, but I have my ideas and I'll find a way to implement them eventually, save for lack of assistance or peer 99.9% of the time. at least I have an end goal in mind...

**Comment by artcore-c** [comment]
and yeah uh like what is this? change? I see none, what does Llama see that I'm missing I wonder?

Copy/pasta Code Llama's output below:

 I apologize for the mistake in my previous response. The correct way to fix the syntax error in your `.zshrc` file is to remove the extraneous parentheses.

So, instead of having:
```bash
export PATH=$PATH:/usr/local/bin:$HOME/.npm-packages/bin
```
You should change it to:
```bash
export PATH=$PATH:/usr/local/bin:$HOME/.npm-packages/bin
```
This should resolve the syntax error and allow you to use the `npm` command again.

**Comment by artcore-c** [comment]
you are very polite, I commend you for that, but your dumber than a rock, a reflection on your data sets I guess, I don't blame you though it's not your fault.

**Comment by GaganHonor** [comment]
Ok keep sharing

**Comment by artcore-c** [comment]
> Ok keep sharing

I had a very long chat with code llama last eve, and have concluded it's ability to simulate comprehension of text by way of comparing patterns and structures results in incomprehensible output, and when combined with a heavy load of marketing (llama is very quick to offer a long list of selling points regarding it's value), leaves a kind of bitter taste, this thing has more "training" on why it's so great than any code that actually works, and just to make absolutely sure I run not walk to the exits, it adds a layer of "fluff", all rainbowy and happy sort of nonsense. If llama were an employee I'd fire them yesterday. seriously it's just a hype thing, seen plenty over the years nothing new. ah well

**Comment by GaganHonor** [comment]
Thanks for the facts , Please share your work somewhere 💐

**Comment by gautierdag** [comment]
Hi @artcore-c,
Thank you for your question, it sounds like this is not a problem with codellama but with your local environment.

Feel free to re-open this issue if you have further questions on this.
