### ISSUE TITLE
Doesn't codellama know when to stop? The EOS doesn't work?

### ISSUE THREAD

**Issue by activezhao** [meta-llama/codellama#89]
I just use the codellama-7b，and I found that it won't stop until it reaches the max_tokens.
So how to solve this problem? Thank u !

Here are a few examples of what I tested:

`curl http://localhost:8000/v1/completions     -H "Content-Type: application/json"     -d '{
        "model": "codeLlama",
        "prompt": "San Francisco is a",
        "max_tokens": 50,
        "temperature": 0
    }'
{"id":"cmpl-df1438614f2a42369f20d240dad02ba0","object":"text_completion","created":1693811331,"model":"codeLlama","choices":[{"index":0,"text":"city of 800,000 people, and the largest city in the state of California. The city is located on the west coast of the United States, and is the cultural and economic center of the San Francisco Bay Area.\n","logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":5,"total_tokens":55,"completion_tokens":50}}`

`curl http://localhost:8000/v1/completions     -H "Content-Type: application/json"     -d '{
        "model": "codeLlama",
        "prompt": "San Francisco is a",
        "max_tokens": 500,
        "temperature": 0
    }'
{"id":"cmpl-577731d1354a4b34a17a824f137c4d40","object":"text_completion","created":1693811355,"model":"codeLlama","choices":[{"index":0,"text":"city of 800,000 people, and the largest city in the state of California. The city is located on the west coast of the United States, and is the cultural and economic center of the San Francisco Bay Area.\nThe city is known for its many parks, including Golden Gate Park, which is the largest park in the United States. The city is also known for its many museums, including the San Francisco Museum of Modern Art, the San Francisco Museum of Art, the California Academy of Sciences, the de Young Museum, and the Legion of Honor.\nThe city is also known for its many restaurants, including the iconic Chinatown, the Mission District, and the North Beach area.\nThe city is also known for its many sports teams, including the San Francisco 49ers, the San Francisco Giants, the San Francisco Warriors, the San Francisco Seals, and the San Francisco Giants.\nThe city is also known for its many beaches, including the Golden Gate Bridge, the Golden Gate Park, the Golden Gate, the Pacific Ocean, the San Francisco Bay, and the San Francisco Bay Bridge.\nThe city is also known for its many landmarks, including the Golden Gate Bridge, the Golden Gate Park, the Golden Gate, the Pacific Ocean, the San Francisco Bay, and the San Francisco Bay Bridge.\nThe city is also known for its many attractions, including the Golden Gate Bridge, the Golden Gate Park, the Golden Gate, the Pacific Ocean, the San Francisco Bay, and the San Francisco Bay Bridge.\nThe city is also known for its many hotels, including the Fairmont San Francisco, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fairmont San Francisco Marriott, the Fair","logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":5,"total_tokens":505,"completion_tokens":500}}`

**Comment by AdarshAcharya5** [comment]
Hi, I'm relatively new here, but here is my analysis:
In model.py, the max_seq_len is  :

![Screenshot from 2023-09-04 15-00-29_2](https://github.com/facebookresearch/codellama/assets/132294330/5562ef48-4dd0-486a-ac7a-47e8aee095c2)

Here, based on your prompt, the total generation length is calculated as min(2048, 500 + 5). Hence giving 500 completion tokens.

![Screenshot from 2023-09-04 15-01-57_2](https://github.com/facebookresearch/codellama/assets/132294330/38c26e37-fd62-44c3-80d3-cc57c1e71976)

The loop runs from min_prompt_len (0 probably) to total_len value (505 in your example).

![Screenshot from 2023-09-04 15-02-28_2](https://github.com/facebookresearch/codellama/assets/132294330/a8ec2679-20e6-43d0-a648-bfaadd3b56ab)

The code for breaking the generation loop when eos token is reached : 

![Screenshot from 2023-09-04 15-36-42_2](https://github.com/facebookresearch/codellama/assets/132294330/bef44c54-e316-40ce-b89d-049dfcb9ae2b)

stop_reached is a tensor of length prompt_tokens, and based on this snippet and my reading, I'm assuming that if the current token_id is a pad_id and the next_token is an eos_token, the corresponding position in the stop_reached tensor would become True. The generation only breaks if all the values in stop_reached tensor becomes True, which may not be happening in your example. I understand that this may not answer your question and that I may be pointing out the obvious, but I hope it helps in some way!. The last snippet is hard for me to understand as well, and I would appreciate if someone could explain it to me as well! :).

**Comment by jgehring** [comment]
Hi @activezhao, I'm not sure which code-base you're using here; this repository does not offer an HTTP API. Also, you're asking for a natural text completion rather than code generation.

That being said, when experiencing generations that are too long you can try to use the instruct models or implement a custom stopping criterion based on, e.g., paragraphs or newlines.

Feel free to re-open this issue if you have further questions.

**Comment by activezhao** [comment]
> Hi @activezhao, I'm not sure which code-base you're using here; this repository does not offer an HTTP API. Also, you're asking for a natural text completion rather than code generation.
> 
> That being said, when experiencing generations that are too long you can try to use the instruct models or implement a custom stopping criterion based on, e.g., paragraphs or newlines.
> 
> Feel free to re-open this issue if you have further questions.

Hi, @jgehring , thanks for your answer, I just use CodeLlama-7b and for code generation, and I use vLLM to deploy it.

But, when I ask a question of code completion, the response always ends with many \n\n\n\n or \t\t\t\t, It doesn't know it should stop now. Because of no EOS effects, we have to limit the value of "max_tokens" and use "stop" param to let infer stop, this is actually very inconvenient.

I'm curious why the code completion scenario doesn't work in EOS?

**Comment by activezhao** [comment]
> Hi, I'm relatively new here, but here is my analysis: In model.py, the max_seq_len is :
> 
> ![Screenshot from 2023-09-04 15-00-29_2](https://user-images.githubusercontent.com/132294330/265419381-5562ef48-4dd0-486a-ac7a-47e8aee095c2.png)
> 
> Here, based on your prompt, the total generation length is calculated as min(2048, 500 + 5). Hence giving 500 completion tokens.
> 
> ![Screenshot from 2023-09-04 15-01-57_2](https://user-images.githubusercontent.com/132294330/265419770-38c26e37-fd62-44c3-80d3-cc57c1e71976.png)
> 
> The loop runs from min_prompt_len (0 probably) to total_len value (505 in your example).
> 
> ![Screenshot from 2023-09-04 15-02-28_2](https://user-images.githubusercontent.com/132294330/265420346-a8ec2679-20e6-43d0-a648-bfaadd3b56ab.png)
> 
> The code for breaking the generation loop when eos token is reached :
> 
> ![Screenshot from 2023-09-04 15-36-42_2](https://user-images.githubusercontent.com/132294330/265427688-bef44c54-e316-40ce-b89d-049dfcb9ae2b.png)
> 
> stop_reached is a tensor of length prompt_tokens, and based on this snippet and my reading, I'm assuming that if the current token_id is a pad_id and the next_token is an eos_token, the corresponding position in the stop_reached tensor would become True. The generation only breaks if all the values in stop_reached tensor becomes True, which may not be happening in your example. I understand that this may not answer your question and that I may be pointing out the obvious, but I hope it helps in some way!. The last snippet is hard for me to understand as well, and I would appreciate if someone could explain it to me as well! :).

Hi, @AdarshAcharya5,  thanks for your answer about the code analysis, u r so good, I have learnt a lot, I will still try to know how to get the EOS works.

**Comment by yangzhj53** [comment]
> > Hi @activezhao, I'm not sure which code-base you're using here; this repository does not offer an HTTP API. Also, you're asking for a natural text completion rather than code generation.
> > That being said, when experiencing generations that are too long you can try to use the instruct models or implement a custom stopping criterion based on, e.g., paragraphs or newlines.
> > Feel free to re-open this issue if you have further questions.
> 
> Hi, @jgehring , thanks for your answer, I just use CodeLlama-7b and for code generation, and I use vLLM to deploy it.
> 
> But, when I ask a question of code completion, the response always ends with many \n\n\n\n or \t\t\t\t, It doesn't know it should stop now. Because of no EOS effects, we have to limit the value of "max_tokens" and use "stop" param to let infer stop, this is actually very inconvenient.
> 
> I'm curious why the code completion scenario doesn't work in EOS?

Hi, I meet the same question that many '\n\n\n\n' outputed and I wanna know if you have solved it.

**Comment by activezhao** [comment]
> > > Hi @activezhao, I'm not sure which code-base you're using here; this repository does not offer an HTTP API. Also, you're asking for a natural text completion rather than code generation.
> > > That being said, when experiencing generations that are too long you can try to use the instruct models or implement a custom stopping criterion based on, e.g., paragraphs or newlines.
> > > Feel free to re-open this issue if you have further questions.
> > 
> > 
> > Hi, @jgehring , thanks for your answer, I just use CodeLlama-7b and for code generation, and I use vLLM to deploy it.
> > But, when I ask a question of code completion, the response always ends with many \n\n\n\n or \t\t\t\t, It doesn't know it should stop now. Because of no EOS effects, we have to limit the value of "max_tokens" and use "stop" param to let infer stop, this is actually very inconvenient.
> > I'm curious why the code completion scenario doesn't work in EOS?
> 
> Hi, I meet the same question that many '\n\n\n\n' outputed and I wanna know if you have solved it.

No, I have not solved it, but I use ”stop“ parameter setting several "\n", such as "\n\n\n\n\n" to let infer stop early.

But, in fact, I have no better ideas.

**Comment by yangzhj53** [comment]
> > > > Hi @activezhao, I'm not sure which code-base you're using here; this repository does not offer an HTTP API. Also, you're asking for a natural text completion rather than code generation.
> > > > That being said, when experiencing generations that are too long you can try to use the instruct models or implement a custom stopping criterion based on, e.g., paragraphs or newlines.
> > > > Feel free to re-open this issue if you have further questions.
> > > 
> > > 
> > > Hi, @jgehring , thanks for your answer, I just use CodeLlama-7b and for code generation, and I use vLLM to deploy it.
> > > But, when I ask a question of code completion, the response always ends with many \n\n\n\n or \t\t\t\t, It doesn't know it should stop now. Because of no EOS effects, we have to limit the value of "max_tokens" and use "stop" param to let infer stop, this is actually very inconvenient.
> > > I'm curious why the code completion scenario doesn't work in EOS?
> > 
> > 
> > Hi, I meet the same question that many '\n\n\n\n' outputed and I wanna know if you have solved it.
> 
> No, I have not solved it, but I use ”stop“ parameter setting several "\n", such as "\n\n\n\n\n" to let infer stop early.
> 
> But, in fact, I have no better ideas.

Thanks for your response, but it seems no "stop" parameter in any function, could you tell me the detail or have you modified the code?

**Comment by activezhao** [comment]
> > > > > Hi @activezhao, I'm not sure which code-base you're using here; this repository does not offer an HTTP API. Also, you're asking for a natural text completion rather than code generation.
> > > > > That being said, when experiencing generations that are too long you can try to use the instruct models or implement a custom stopping criterion based on, e.g., paragraphs or newlines.
> > > > > Feel free to re-open this issue if you have further questions.
> > > > 
> > > > 
> > > > Hi, @jgehring , thanks for your answer, I just use CodeLlama-7b and for code generation, and I use vLLM to deploy it.
> > > > But, when I ask a question of code completion, the response always ends with many \n\n\n\n or \t\t\t\t, It doesn't know it should stop now. Because of no EOS effects, we have to limit the value of "max_tokens" and use "stop" param to let infer stop, this is actually very inconvenient.
> > > > I'm curious why the code completion scenario doesn't work in EOS?
> > > 
> > > 
> > > Hi, I meet the same question that many '\n\n\n\n' outputed and I wanna know if you have solved it.
> > 
> > No, I have not solved it, but I use ”stop“ parameter setting several "\n", such as "\n\n\n\n\n" to let infer stop early.
> > 
> > But, in fact, I have no better ideas.
> 
> Thanks for your response, but it seems no "stop" parameter in any function, could you tell me the detail or have you modified the code?

I depoley codeLlama with vLLM，and the request parameters have a parameter named "stop", the infer will stop early when the next token is the "stop" words, u can just see the doc of vLLM.

**Comment by yangzhj53** [comment]
> > > > > > Hi @activezhao, I'm not sure which code-base you're using here; this repository does not offer an HTTP API. Also, you're asking for a natural text completion rather than code generation.
> > > > > > That being said, when experiencing generations that are too long you can try to use the instruct models or implement a custom stopping criterion based on, e.g., paragraphs or newlines.
> > > > > > Feel free to re-open this issue if you have further questions.
> > > > > 
> > > > > 
> > > > > Hi, @jgehring , thanks for your answer, I just use CodeLlama-7b and for code generation, and I use vLLM to deploy it.
> > > > > But, when I ask a question of code completion, the response always ends with many \n\n\n\n or \t\t\t\t, It doesn't know it should stop now. Because of no EOS effects, we have to limit the value of "max_tokens" and use "stop" param to let infer stop, this is actually very inconvenient.
> > > > > I'm curious why the code completion scenario doesn't work in EOS?
> > > > 
> > > > 
> > > > Hi, I meet the same question that many '\n\n\n\n' outputed and I wanna know if you have solved it.
> > > 
> > > 
> > > No, I have not solved it, but I use ”stop“ parameter setting several "\n", such as "\n\n\n\n\n" to let infer stop early.
> > > But, in fact, I have no better ideas.
> > 
> > 
> > Thanks for your response, but it seems no "stop" parameter in any function, could you tell me the detail or have you modified the code?
> 
> I depoley codeLlama with vLLM，and the request parameters have a parameter named "stop", the infer will stop early when the next token is the "stop" words, u can just see the doc of vLLM.

I see. Thanks!
