### ISSUE TITLE
Any plans to put this on Replicate?

### ISSUE THREAD

**Issue by carolinefrasca** [meta-llama/codellama#9]
Would love to be able to use this on [Replicate](https://replicate.com/facebookresearch) – are there any plans for Facebook Research to upload this there?

Thank you!

**Comment by GaganHonor** [comment]
Already available on AWS EC2 and HuggingFace 

[AWS](https://aws.amazon.com/blogs/machine-learning/llama-2-foundation-models-from-meta-are-now-available-in-amazon-sagemaker-jumpstart/)
[HF🤗](https://huggingface.co/blog/codellama#conversational-instructions)

And , Yes, CodeLlama is available on Replicate. [You can run CodeLlama models with an API on Replicate](https://www.bing.com/search?form=NTPCHB&q=Bing+AI&showconv=1#)[1](https://replicate.com/replicate/codellama-13b). [For example, you can run the CodeLlama-13b model, which is a 13b parameter Llama model tuned for code completion](https://replicate.com/replicate/codellama-13b)[1](https://replicate.com/replicate/codellama-13b). [You can also run the CodeLlama-7b-Instruct model, which is a 7b parameter Llama model tuned for chatting about code](https://replicate.com/replicate/codellama-7b-instruct)

Thanks for Reading my answer @carolinedlu mam , I am honored. 🌟

**Comment by baptisteroziere** [comment]
Thanks @GaganHonor for answering. I am closing this issue now, please feel free to reopen if needed.

**Comment by GaganHonor** [comment]
Thanks for your kind words @brozi .
