### ISSUE TITLE
How can I fine-tuning codellama with our own dataset?

### ISSUE THREAD

**Issue by Hkh9966** [meta-llama/codellama#92]
As title. Is there any way to achieve that?

**Comment by zachschillaci27** [comment]
This depends, what kind of fine-tuning do you want to do? What does your dataset consist of? If it's instruction tuning or RLHF then there's a good reference available here: https://towardsdatascience.com/fine-tune-your-own-llama-2-model-in-a-colab-notebook-df9823a04a32. If you provide more information I can try to be of more help.

**Comment by Hkh9966** [comment]
We have our own code repo, so we wanted to leverage fine-tune to have our own code generation model.

**Comment by jgehring** [comment]
Hi @Hkh9966, fine-tuning functionality is not included in this code-base. I suggest using other software packages for this and maybe following tutorials available online. For example, most tutorials on fine-tuning Llama 2 or models from HuggingFace will also apply to Code Llama.
