### ISSUE TITLE
Can't run codellama!

### ISSUE THREAD

**Issue by adnanwahab** [meta-llama/codellama#95]
```
(py465) awahab@adnna:~/nexus-collaborative-project-planning-merge-notes/codellama$ torchrun --nproc_per_node 1 example_completion.py     --ckpt_dir CodeLlama-34b-Instruct/     --tokenizer_path CodeLlama-7b-Instruct/tokenizer.model     --max_seq_len 512
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/awahab/nexus-collaborative-project-planning-merge-notes/codellama/example_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/home/awahab/anaconda3/envs/py465/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/awahab/anaconda3/envs/py465/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/awahab/anaconda3/envs/py465/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/awahab/nexus-collaborative-project-planning-merge-notes/codellama/example_completion.py", line 20, in main
    generator = Llama.build(
  File "/home/awahab/nexus-collaborative-project-planning-merge-notes/codellama/llama/generation.py", line 86, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=4 but world size is 1
```

this is my error when running the ahove

**Comment by bank010** [comment]
> ```
> (py465) awahab@adnna:~/nexus-collaborative-project-planning-merge-notes/codellama$ torchrun --nproc_per_node 1 example_completion.py     --ckpt_dir CodeLlama-34b-Instruct/     --tokenizer_path CodeLlama-7b-Instruct/tokenizer.model     --max_seq_len 512
> > initializing model parallel with size 1
> > initializing ddp with size 1
> > initializing pipeline with size 1
> Traceback (most recent call last):
>   File "/home/awahab/nexus-collaborative-project-planning-merge-notes/codellama/example_completion.py", line 55, in <module>
>     fire.Fire(main)
>   File "/home/awahab/anaconda3/envs/py465/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/home/awahab/anaconda3/envs/py465/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "/home/awahab/anaconda3/envs/py465/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/home/awahab/nexus-collaborative-project-planning-merge-notes/codellama/example_completion.py", line 20, in main
>     generator = Llama.build(
>   File "/home/awahab/nexus-collaborative-project-planning-merge-notes/codellama/llama/generation.py", line 86, in build
>     assert model_parallel_size == len(
> AssertionError: Loading a checkpoint for MP=4 but world size is 1
> ```
> 
> 这是我运行 AHOVE 时的错误

torchrun --nproc_per_node 4 example_completion.py     --ckpt_dir CodeLlama-34b-Instruct/     --tokenizer_path CodeLlama-7b-Instruct/tokenizer.model     --max_seq_len 512

**Comment by RuiLvCOMCEO** [comment]
anacorda prompt,python3.9,
(cuda118) G:\Projects\llama\CodeLlama>torchrun --nproc_per_node 4 example_instructions.py --ckpt_dir CodeLlama-34b-Instruct/ --tokenizer_path CodeLlama-34b-Instruct/tokenizer.model --max_seq_len 512 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [ActiViz]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [ActiViz]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [ActiViz]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [ActiViz]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [ActiViz]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [ActiViz]:29500 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "G:\Projects\llama\CodeLlama\example_instructions.py", line 68, in <module>
Traceback (most recent call last):
  File "G:\Projects\llama\CodeLlama\example_instructions.py", line 68, in <module>
    fire.Fire(main)
fire.Fire(main)
  File "D:\Anaconda3\envs\cuda118\Lib\site-packages\fire\core.py", line 141, in Fire
  File "D:\Anaconda3\envs\cuda118\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
component_trace = _Fire(component, args, parsed_flag_args, context, name)

**Comment by jgehring** [comment]
As mentioned by @bank010, the 34b model needs to be run with `--nproc_per_node 4`.

@RuiLvCOMCEO, your issue seems to relate to running Code Llama on Windows; see #32 for more info and a potential solution, and please use that issue for further discussion.
